# Sandtrap Item List

sandtrapItems = {
    # MV Vehicle Pallette
    0: "Banshee",
    1: "Chopper",
    2: "Hornet",
    3: "Ghost",
    4: "Prowler",
    5: "Mongoose",
    6: "Scorpion",
    7: "Warthog",
    8: "Warthog, Gauss",
    9: "Wraith",

    # MV Weapon Pallette
    10: "Assault Rifle",
    11: "Battle Rifle",
    12: "Shotgun",
    13: "Sniper Rifle",
    14: "SMG",
    15: "Spiker",
    16: "Magnum",
    17: "Plasma Pistol",
    18: "Needler",
    19: "Beam Rifle",
    20: "Brute Shot",
    21: "Rocket Launcher",
    22: "Spartan Laser",
    23: "Energy Sword",
    24: "Machine Gun Turret",
    25: "Gravity Hammer",
    26: "Missile Pod",
    27: "Sentinel Beam",
    28: "Fuel Rod Gun",
    29: "Carbine",
    30: "Mauler",
    31: "plasma Rifle",
    32: "Silenced SMG",
    33: "Automag",
    34: "Brute Plasma Rifle",
    35: "Plasma Cannon",
    36: "Flamethrower",
    37: "7-Wood",

    # MV Equipment Pallette
    38: "Frag Grenade",
    39: "Plasma Grenade",
    40: "Spike Grenade",
    41: "Firebomb Grenade",
    42: "Bubble Shield",
    43: "Power Drain",
    44: "Trip Mine",
    45: "Grav Lift",
    46: "Regenerator",
    47: "Radar Jammer",
    48: "Flare",
    49: "Deployable Cover",
    50: "Overshields",
    51: "Active Camo",
    52: "Custom Powerup",
    53: "Auto-Turret",
    55: "Invincibility",
    56: "Cloaking",

    # MV Scenery Pallette
    57: "Fusion Coil",
    58: "Crate, Single",
    59: "Crate",
    60: "Turret Case",
    61: "Radio Antennae",
    62: "Camping Stool",
    63: "Drum, 55 Gal",
    64: "Equipment case",
    65: "Radio Set, Small",
    66: "Drop Pod, Closed",
    67: "Drop Pod, Panel",
    68: "Barricade",
    69: "Medical Crate",
    70: "Computer, Small",
    71: "Rucksack",
    72: "Blitz Can",
    73: "Barrel",
    74: "Barrel, Small",
    75: "Supply Case",
    76: "Plasma Battery",
    77: "Grav Lift",
    78: "Weapon Holder",

    # MV Teleporter Pallette
    79: "Sender Node",
    80: "Receiver Node",
    81: "Two-Way Node",

    # MV Goals Pallette
    82: "CTF Spoawn Point",
    83: "CTF Return Area",
    84: "Assault Spawn Point",
    85: "Assault Goal Area",
    86: "Juggernaut Destination Static",
    87: "Hill Static",
    88: "Oddball Spawn Point",
    89: "Territory Static",
    90: "VIP Destination Static",


    # MV Spawners Pallette
    91: "Respawn Point",
    92: "Assault Initial Spawn Point",
    93: "CTF Initial Spawn Point",
    94: "Hill Initial Spawn Point",
    95: "Oddball Initial Spawn Point",
    96: "Slayer Initial Spawn Point",
    97: "Territories Initial Spawn Point",
    98: "VIP Initial Spawn Point",
    99: "Assault Respawn Zone",
    100: "CTF Respawn Zone",
    101: "CTF Flag At Home Respawn Zone",
    102: "CTF Flag Away Respawn Zone",
    103: "Hill Respawn Zone",
    104: "Oddball Respawn Zone",
    105: "Slayer Respawn Zone",
    106: "Territories Respawn Zone",
    107: "VIP Respawn Zone",
    108: "Infection Initial Spawn Point",
    109: "Infection Respawn Zone"
}
