# Ghosttown Item List

ghosttownItems = {
    # MV Vehicle Pallette
    0: "Ghost",
    1: "Mongoose",

    # MV Weapon Pallette
    2: "Energy Sword",
    3: "Magnum",
    4: "Needler",
    5: "Plasma Pistol",
    6: "Assault Rifle",
    7: "Battle Rifle",
    8: "Carbine",
    9: "Shotgun",
    10: "SMG",
    11: "Sniper Rifle",
    12: "Spiker",
    13: "Rocket Launcher",
    14: "Spartan Laser",
    15: "Brute shot",
    16: "Machinegun Turret",
    17: "Plasma Cannon",
    18: "Gravity Hammer",
    19: "Mauler",
    20: "Beam Rifle",
    21: "Plasma Rifle",
    22: "Fuel Rod Gun",
    23: "Sentinel Beam",
    24: "Flamethrower",
    25: "Silenced SMG",
    26: "Automag",
    27: "Brute Plasma Rifle",
    28: "Missile Pod",
    29: "7-Wood",
   
   # MV Equipment Pallette
    30: "Frag Grenade",
    31: "Plasma Grenade",
    32: "Spike Grenade",
    33: "Firebomb Grenade",
    34: "Bubble Shield",
    35: "Power Drain",
    36: "Trip Mine",
    37: "Grav Lift",
    38: "Regenerator",
    39: "Radar Jammer",
    40: "Flare",
    41: "Deployable Cover",
    42: "Overshields",
    43: "Active Camo",
    44: "Custom Powerup",
    45: "Auto-Turret",
    46: "Invincibility",
    47: "Cloaking",

    # MV Scenery Pallette
    48: "Fusion Coil",
    49: "Barrel, Small",
    50: "Fence Wall",
    51: "Wire Spool",
    52: "Water Crate",
    53: "Door",
    54: "Water Barrel",
    55: "Single Box, Open",
    56: "Stairs",
    57: "Pallet",
    58: "Bridge",
    59: "Street Cone",
    60: "Barrier",
    61: "Barrier, Short",
    62: "Barricade",
    63: "Propane Tank",
    64: "Watchtower Base",
    65: "Ramp",
    66: "Weapon Holder",
    67: "Grav Lift",
    68: "Shield Door, Large",
    69: "Shield Door",
    70: "Cannon, Man",
    71: "Soccer Ball",
    72: "FX, Nova",
    73: "FX, Pen And Ink",
    74: "FX, Olde Timey",
    75: "FX, Colorblind",
    76: "FX, Gloomy",
    77: "FX, Juicy",
    

    # MV Teleporters Pallette
    78: "Sender Node",
    79: "Receiver Node",
    80: "Two-Way Node",

    # MV Goals Pallette
    81: "Respawn Point",
    82: "CTF Flag Spawn Point",
    83: "CTF Flag Return Area",
    84: "Assault Bomb Spawn Point",
    85: "Assault Bomb Goal Area",
    86: "Juggernaut Destination Static",
    87: "Hill Static",
    88: "Oddball Spawn Point",
    89: "Territory Static",
    90: "VIP Destination Static",


    # MV Spawners Pallette
    91: "Assault Initial Spawn Point",
    92: "CTF Initial Spawn Point",
    93: "Hill Initial Spawn Point",
    94: "Oddball Initial Spawn Point",
    95: "Slayer Initial Spawn Point",
    96: "Territories Initial Spawn Point",
    97: "VIP Initial Spawn Point",
    98: "Assault Respawn Zone",
    99: "CTF Respawn Zone",
    100: "CTF Flag At Home Respawn Zone",
    101: "CTF Flag Away Respawn Zone",
    102: "Hill Respawn Zone",
    103: "Oddball Respawn Zone",
    104: "Slayer Respawn Zone",
    105: "Territories Respawn Zone",
    106: "VIP Respawn Zone",
    107: "Infection Initial Spawn Point",
    108: "Infection Respawn Zone",

    109: "Respawn Point Invisible",
    110: "box_l",
    111: "box_m",
    112: "box_xl",
    113: "box_xxl",
    114: "box_xxxl",
    115: "wall_l",
    116: "wall_m",
    117: "wall_xl",
    118: "wall_xxl",
    119: "wall_xxxl"
}
