# Epitaph Item List

epitaphItems = {
    # MV Vehicle Pallette
    0: "Mongoose",

    # MV Weapon Pallette
    1: "Assault Rifle",
    2: "Battle Rifle",
    3: "Shotgun",
    4: "Sniper Rifle",
    5: "SMG",
    6: "Spiker",
    7: "Magnum",
    8: "Plasma Pistol",
    9: "Plasma Rifle",
    10: "Needler",
    11: "Brute Shot",
    12: "Rocket Launcher",
    13: "Spartan Laser",
    14: "Energy Sword",
    15: "Plasma Cannon",
    16: "Gravity Hammer",
    17: "Carbine",
    18: "Mauler",
    19: "Machine Gun Turret",
    20: "Fuel Rod Gun",
    21: "Flamethrower",
    22: "Beam Rifle",
    23: "Sentinel Beam",
    24: "Silenced SMG",
    25: "Automag",
    26: "Brute Plasma Rifle",
    27: "Missile Pod",
    28: "7-Wood",

    # MV Equipment Pallette
    29: "Frag Grenade",
    30: "Plasma Grenade",
    31: "Spike Grenade",
    32: "Firebomb Grenade",
    33: "Bubble Shield",
    34: "Power Drain",
    35: "Trip Mine",
    36: "Grav Lift",
    37: "Regenerator",
    38: "Radar Jammer",
    39: "Flare",
    40: "Deployable Cover",
    41: "Overshields",
    42: "Active Camo",
    43: "Custom Powerup",
    44: "Auto-Turret",
    45: "Invincibility",
    46: "Cloaking",

    # MV Scenery Pallette
    47: "Ammo Case",
    48: "Barrier",
    49: "Barrier, Short",
    50: "Barrel",
    51: "Barrel, Small",
    52: "Roadblock",
    53: "Street Cone",
    54: "Pallet",
    55: "Camping Stool",
    56: "Crate, Single",
    57: "Crate",
    58: "Radio Set",
    59: "Fusion Coil",
    60: "Generator, Small",
    61: "Turret Case",
    62: "Ammo Crate",
    63: "Drum, 12 Gal",
    64: "Drum, 55 Gal",
    65: "Weapon Holder",
    66: "Grav Lift",

    # MV Teleporter Pallette
    67: "Sender Node",
    68: "Receiver Node",
    69: "Two-Way Node",

    # MV Goals Pallette
    70: "CTF Spoawn Point",
    71: "CTF Return Area",
    72: "Assault Spawn Point",
    73: "Assault Goal Area",
    74: "Juggernaut Destination Static",
    75: "Hill Static",
    76: "Oddball Spawn Point",
    77: "Territory Static",
    78: "VIP Destination Static",

    # MV Spawners Pallette
    79: "Respawn Point",
    80: "Assault Initial Spawn Point",
    81: "CTF Initial Spawn Point",
    82: "Hill Initial Spawn Point",
    83: "Oddball Initial Spawn Point",
    84: "Slayer Initial Spawn Point",
    85: "Territories Initial Spawn Point",
    86: "VIP Initial Spawn Point",
    87: "Assault Respawn Zone",
    88: "CTF Respawn Zone",
    89: "CTF Flag At Home Respawn Zone",
    90: "CTF Flag Away Respawn Zone",
    91: "Hill Respawn Zone",
    92: "Oddball Respawn Zone",
    93: "Slayer Respawn Zone",
    94: "Territories Respawn Zone",
    95: "VIP Respawn Zone",
    96: "Infection Initial Spawn Point",
    97: "Infection Respawn Zone"

}
