# The Pit Item List

pitItems = {
    # MV Vehicle Pallette
    0: "Mongoose",
    1: "Ghost",

    # MV Weapon Pallette
    2: "Assault Rifle",
    3: "Battle Rifle",
    4: "Shotgun",
    5: "Sniper Rifle",
    6: "SMG",
    7: "Spiker",
    8: "Magnum",
    9: "Plasma Pistol",
    10: "Plasma Rifle",
    11: "Needler",
    12: "Brute Shot",
    13: "Rocket Launcher",
    14: "Spartan Laser",
    15: "Energy Sword",
    16: "Machine Gun Turret",
    17: "Gravity Hammer",
    18: "Mauler",
    19: "Flamethrower",
    20: "Fuel Rod Gun",
    21: "Beam Rifle",
    22: "Sentinel Beam",
    23: "Carbine",
    24: "Silenced SMG",
    25: "Automag",
    26: "Brute Plasma Rifle",
    27: "Plasma Cannon",
    28: "Missile Pod",
    29: "7-Wood",

    # MV Equipment Pallette
    30: "Frag Grenade",
    31: "Plasma Grenade",
    32: "Spike Grenade",
    33: "Firebomb Grenade",
    34: "Bubble Shield",
    35: "Power Drain",
    36: "Trip Mine",
    37: "Grav Lift",
    38: "Regenerator",
    39: "Radar Jammer",
    40: "Flare",
    41: "Deployable Cover",
    42: "Overshields",
    43: "Active Camo",
    44: "Custom Powerup",
    45: "Auto-Turret",
    46: "Invincibility",
    47: "Cloaking",

    # MV Scenery Pallette
    48: "Fusion Coil",
    49: "Ammo Case",
    50: "Camping Stool",
    51: "Crate",
    52: "Generator, Small",
    53: "Floodlights",
    54: "Generator",
    55: "Barrel",
    56: "Barrel, Small",
    57: "Locker",
    58: "Barrier",
    59: "Barrier, Short",
    60: "Missile, Body",
    61: "Missile, Warhead",
    62: "Pallet",
    63: "Roadblock",
    64: "Street Cone",
    65: "Toolbox, Small",
    66: "Toolbox",
    67: "Rucksack",
    68: "Propane Tank",
    69: "Weapon Holder",
    70: "Grav Lift",

    # MV Teleporter Pallette
    71: "Sender Node",
    72: "Receiver Node",
    73: "Two-Way Node",

    # MV Goals Pallette
    74: "Respawn Point",
    75: "CTF Spawn Point",
    76: "CTF Return Area",
    77: "Assault Spawn Point",
    78: "Assault Goal Area",
    79: "Juggernaut Destination Static",
    80: "Hill Static",
    81: "Oddball Spawn Point",
    82: "Territory Static",
    83: "VIP Destination Static",

    # MV Spawners Pallette
    84: "Assault Initial Spawn Point",
    85: "CTF Initial Spawn Point",
    86: "Hill Initial Spawn Point",
    87: "Oddball Initial Spawn Point",
    88: "Slayer Initial Spawn Point",
    89: "Territories Initial Spawn Point",
    90: "VIP Initial Spawn Point",
    91: "Assault Respawn Zone",
    92: "CTF Respawn Zone",
    93: "CTF Flag At Home Respawn Zone",
    94: "CTF Flag Away Respawn Zone",
    95: "Hill Respawn Zone",
    96: "Oddball Respawn Zone",
    97: "Slayer Respawn Zone",
    98: "Territories Respawn Zone",
    99: "VIP Respawn Zone",
    100: "Infection Initial Spawn Point",
    101: "Infection Respawn Zone",

    102: "Warthog",
    103: "Security Camera",
    104: "Respawn Point Invisible",
    105: "Generator, Heavy",
    106: "Wall, Phone",
    107: "Forklift",
    108: "box_l",
    109: "box_m",
    110: "box_xl",
    111: "box_xxl",
    112: "box_xxxl",
    113: "wall_l",
    114: "wall_m",
    115: "wall_xl",
    116: "wall_xxl",
    117: "wall_xxxl",

}
