# Standoff Item List

standoffItems = {
    0: "Ghost",
    1: "Mongoose",
    2: "Warthog",
    3: "Chopper",
    4: "Banshee",
    5: "Wraith",
    6: "Warthog, Gauss",
   

    7: "Energy Sword",
    8: "Magnum",
    9: "Needler",
    10: "Plasma Pistol",
    11: "Assault Rifle",
    12: "Battle Rifle",
    13: "Carbine",
    14: "Shotgun",
    15: "SMG",
    16: "Sniper Rifle",
    17: "Spiker",
    18: "Rocket Launcher",
    19: "Spartan Laser",
    20: "Brute shot",
    21: "Machinegun Turret",
    22: "Plasma Cannon",
    23: "Gravity Hammer",
    24: "Fuel Rod Gun",
    25: "Mauler",
    26: "Flamethrower",
    27: "Beam Rifle",
    28: "Sentinel Beam",
    29: "Missile Pod",
    30: "Plasma Rifle",
    31: "Silenced SMG",
    32: "Automag",
    33: "Brute Plasma Rifle",
    34: "Plasma Cannon",
    35: "7-Wood",

    38: "Frag Grenade",
    39: "Plasma Grenade",
    40: "Spike Grenade",
    41: "Firebomb Grenade",
    42: "Bubble Shield",
    43: "Power Drain",
    44: "Trip Mine",
    45: "Grav Lift",
    46: "Regenerator",
    47: "Radar Jammer",
    48: "Flare",
    49: "Deployable Cover",
    50: "Overshields",
    51: "Active Camo",
    52: "Custom Powerup",
    53: "Auto-Turret",
    54: "Invincibility",
    55: "Cloaking",

    # MAP VARIANT SCENERY STARTS
    56: "Fusion Coil",
    57: "Crate",
    58: "Barrel",
    59: "Barrel, Small",
    60: "Crate, Single",
    61: "Camping Stool",
    62: "Radio Antennae",
    63: "Fence Box",
    64: "Drum, 12 Gal",
    65: "Drum, 55 Gal",
    66: "Generator, Small",
    67: "Radio Set",
    68: "Pallet",
    69: "Roadblock",
    70: "Street Cone",
    71: "Barrier",
    72: "Barrier, Short",
    73: "Barricade",
    74: "Propane Tank",
    75: "Missile, Body",
    76: "Forklift",
    77: "Wire Spool",
    78: "Double Box, Open",
    79: "Bridge",
    80: "Weapon Holder",
    81: "Grav Lift",
    82: "Shield Door, Large",
    83: "Shield Door",
    84: "Cannon, Man",
    85: "Soccer Ball",
    

    # MAP VARIANT TELEPORTERS START
    86: "Sender Node",
    87: "Receiver Node",
    88: "Two-Way Node",
    # MAP VARIANT TELEPORTERS END

    # MAP VARIANT SPAWNERS START
    89: "CTF Flag Spawn Point",
    90: "CTF Flag Return Area",
    91: "Assault Bomb Spawn Point",
    92: "Assault Bomb Goal Area",
    93: "Juggernaut Destination Static",
    94: "Hill Static",
    95: "Oddball Spawn Point",
    96: "Territory Static",
    97: "VIP Destination Static",


    98: "Respawn Point",
    99: "Assault Initial Spawn Point",
    100: "CTF Initial Spawn Point",
    101: "Hill Initial Spawn Point",
    102: "Oddball Initial Spawn Point",
    103: "Slayer Initial Spawn Point",
    104: "Territories Initial Spawn Point",
    105: "VIP Initial Spawn Point",
    106: "Assault Respawn Zone",
    107: "CTF Respawn Zone",
    108: "CTF Flag At Home Respawn Zone",
    109: "CTF Flag Away Respawn Zone",
    110: "Hill Respawn Zone",
    111: "Oddball Respawn Zone",
    112: "Slayer Respawn Zone",
    113: "Territories Respawn Zone",
    114: "VIP Respawn Zone",
    115: "Infection Initial Spawn Point",
    116: "Infection Respawn Zone"
}
