# Sandtrap Item List

sandtrapItems = {
    # MV Vehicle Pallette
    0: "Banshee",
    1: "Chopper",
    2: "Hornet",
    3: "Ghost",
    4: "Prowler",
    5: "Mongoose",
    6: "Scorpion",
    7: "Warthog",
    8: "Warthog, Gauss",
    9: "Wraith",

    # MV Weapon Pallette
    10: "Assault Rifle",
    11: "Battle Rifle",
    12: "Shotgun",
    13: "Sniper Rifle",
    14: "SMG",
    15: "Spiker",
    16: "Magnum",
    17: "Plasma Pistol",
    18: "Needler",
    19: "Beam Rifle",
    20: "Brute Shot",
    21: "Rocket Launcher",
    22: "Spartan Laser",
    23: "Energy Sword",
    24: "Machine Gun Turret",
    25: "Gravity Hammer",
    26: "Missile Pod",
    27: "Sentinel Beam",
    28: "Fuel Rod Gun",
    29: "Carbine",
    30: "Mauler",
    31: "plasma Rifle",
    32: "Silenced SMG",
    33: "Automag",
    34: "Brute Plasma Rifle",
    35: "Plasma Cannon",
    36: "Flamethrower",
    37: "7-Wood",

    # MV Equipment Pallette
    38: "Frag Grenade",
    39: "Plasma Grenade",
    40: "Spike Grenade",
    41: "Firebomb Grenade",
    42: "Bubble Shield",
    43: "Power Drain",
    44: "Trip Mine",
    45: "Grav Lift",
    46: "Regenerator",
    47: "Radar Jammer",
    48: "Flare",
    49: "Deployable Cover",
    50: "Overshields",
    51: "Active Camo",
    52: "Custom Powerup",
    53: "Auto-Turret",
    54: "Invincibility",
    55: "Cloaking",

    # MV Scenery Pallette
    56: "Fusion Coil",
    57: "Crate, Single",
    58: "Crate",
    59: "Turret Case",
    60: "Radio Antennae",
    61: "Camping Stool",
    62: "Drum, 55 Gal",
    63: "Equipment Case",
    64: "Radio Set, Small",
    65: "Drop Pod, Closed",
    66: "Drop Pod, Panel",
    67: "Barricade",
    68: "Medical Crate",
    69: "Computer, Small",
    70: "Rucksack",
    71: "Blitz Can",
    72: "Barrel",
    73: "Barrel, Small",
    73: "Supply Case",
    75: "Plasma Battery",
    76: "Grav Lift",
    77: "Weapon Holder",

    # MV Teleporter Pallette
    78: "Sender Node",
    79: "Receiver Node",
    80: "Two-Way Node", 

    # MV Goals Pallette
    81: "Respawn Point",
    82: "CTF Spawn Point",
    83: "CTF Return Area",
    84: "Assault Spawn Point",
    85: "Assault Goal Area",
    86: "Juggernaut Destination Static",
    87: "Hill Static",
    88: "Oddball Spawn Point",
    89: "Territory Static",
    90: "VIP Destination Static",


    # MV Spawners Pallette
    91: "Assault Initial Spawn Point",
    92: "CTF Initial Spawn Point",
    93: "Hill Initial Spawn Point",
    94: "Oddball Initial Spawn Point",
    95: "Slayer Initial Spawn Point",
    96: "Territories Initial Spawn Point",
    97: "VIP Initial Spawn Point",
    98: "Assault Respawn Zone",
    99: "CTF Respawn Zone",
    100: "CTF Flag At Home Respawn Zone",
    101: "CTF Flag Away Respawn Zone",
    102: "Hill Respawn Zone",
    103: "Oddball Respawn Zone",
    104: "Slayer Respawn Zone",
    105: "Territories Respawn Zone",
    106: "VIP Respawn Zone",
    107: "Infection Initial Spawn Point",
    108: "Infection Respawn Zone",

    # 110: "EYE?",
    111: "Respawn Point Invisible",
    112: "box_l",
    113: "box_m",
    114: "box_xl",
    115: "box_xxl",
    116: "box_xxxl",
    117: "wall_l",
    118: "wall_m",
    119: "wall_xl",
    120: "wall_xxl",
    121: "wall_xxxl"
}
