# Last Resort Item List

lastresortItems = {
    # MV Vehicle Pallette
    0: "Warthog",
    1: "Mongoose",
    2: "Ghost",
    3: "Scorpion",
    4: "Warthog, Gauss",

    # MV Weapon Pallette
    5: "Assault Rifle",
    6: "Battle Rifle",
    7: "Shotgun",
    8: "Sniper Rifle",
    9: "SMG",
    10: "Spiker",
    11: "Magnum",
    12: "Plasma Pistol",
    13: "Plasma Rifle",
    14: "Needler",
    15: "Beam Rifle",
    16: "Brute Shot",
    17: "Rocket Launcher",
    18: "Spartan Laser",
    19: "Energy Sword",
    20: "Machine Gun Turret",
    21: "Gravity Hammer",
    22: "Missile Pod",
    23: "Fuel Rod Gun",
    24: "Sentinel Beam",
    25: "Mauler",
    26: "Silenced SMG",
    27: "Automag",
    28: "Brute Plasma Rifle",
    29: "Carbine",
    30: "PLasma Cannon",
    31: "Flamethrower",
    32: "7-Wood",

    # MV Equipment Pallette
    33: "Frag Grenade",
    34: "Plasma Grenade",
    35: "Spike Grenade",
    36: "Firebomb Grenade",
    37: "Bubble Shield",
    38: "Power Drain",
    39: "Trip Mine",
    40: "Grav Lift",
    41: "Regenerator",
    42: "Radar Jammer",
    43: "Flare",
    44: "Deployable Cover",
    45: "Overshields",
    46: "Active Camo",
    47: "Custom Powerup",
    48: "Auto-Turret",
    49: "Invincibility",
    50: "Cloaking",

    # MV Scenery Pallette
    51: "Fusion Coil",
    52: "Crate, Single",
    53: "Crate",
    54: "Turret Case",
    55: "Radio Antennae",
    56: "Camping Stool",
    57: "Drum, 55 Gal",
    58: "Equipment Case",
    59: "Radios Set, Small",
    60: "Contianer",
    61: "Container, Open",
    62: "Street Cone",
    63: "Forklift",
    64: "Barrier",
    65: "Roadblock",
    66: "Pallet",
    67: "Garbage Can",
    68: "Barrel",
    69: "Propane Tank",
    70: "Weapon Holder",
    71: "Grav Lift",

    # MV Teleporter Pallette
    72: "Sender Node",
    73: "Receiver Node",
    74: "Two-Way Node",

    # MV Goals Pallette
    75: "CTF Spoawn Point",
    76: "CTF Return Area",
    77: "Assault Spawn Point",
    78: "Assault Goal Area",
    79: "Juggernaut Destination Static",
    80: "Hill Static",
    81: "Oddball Spawn Point",
    82: "Territory Static",
    83: "VIP Destination Static",

    # MV Spawners Pallette
    84: "Respawn Point",
    85: "Assault Initial Spawn Point",
    86: "CTF Initial Spawn Point",
    87: "Hill Initial Spawn Point",
    88: "Oddball Initial Spawn Point",
    89: "Slayer Initial Spawn Point",
    90: "Territories Initial Spawn Point",
    91: "VIP Initial Spawn Point",
    92: "Assault Respawn Zone",
    93: "CTF Respawn Zone",
    94: "CTF Flag At Home Respawn Zone",
    95: "CTF Flag Away Respawn Zone",
    96: "Hill Respawn Zone",
    97: "Oddball Respawn Zone",
    98: "Slayer Respawn Zone",
    99: "Territories Respawn Zone",
    100: "VIP Respawn Zone",
    101: "Infection Initial Spawn Point",
    102: "Infection Respawn Zone"

}
