# Waterfall Item List

waterfallItems = {
    # MV Vehicle Pallette
    0: "Ghost",
    1: "Mongoose",
    2: "Warthog, Wrecked",
    3: "Warthog",
    4: "Warthog, Gauss",
   
    # MV Weapon Pallette
    5: "Assault Rifle",
    6: "Battle Rifle",
    7: "Shotgun",
    8: "Sniper Rifle",
    9: "SMG",
    10: "Silenced SMG",
    11: "Spiker",
    12: "Magnum",
    13: "Automag",
    14: "Plasma Pistol",
    15: "Plasma Rifle",
    16: "Brute Plasma Rifle",
    17: "Needler",
    18: "Brute Shot",
    19: "Rocket Launcher",
    20: "Spartan Laser",
    21: "Energy Sword",
    22: "Gravity Hammer",
    23: "7-Wood",
    24: "Carbine",
    25: "Mauler",
    26: "Fuel Rod Cannon",
    27: "Sentinel Beam",
    28: "Machine Gun Turret",
    29: "Plasma Cannon",
    30: "Flamethrower",
    31: "Missile Pod",
    32: "Beam Rifle",

    # MV Equipment Pallette
    33: "Frag Grenade",
    34: "Plasma Grenade",
    35: "Spike Grenade",
    36: "Firebomb Grenade",
    37: "Bubble Shield",
    38: "Power Drain",
    39: "Trip Mine",
    40: "Grav Lift",
    41: "Regenerator",
    42: "Radar Jammer",
    43: "Flare",
    44: "Deployable Cover",
    45: "Auto-Turret",
    46: "Overshields",
    47: "Active Camo",
    48: "Custom Powerup",
    49: "SPNKR Ammo",
    50: "Invincibility",
    51: "Cloaking",

    # MV Scenery Pallette
    52: "Supply Case",
    53: "Crate",
    54: "Generator",
    55: "Server",
    56: "Double Box",
    57: "Double Box, Open",
    58: "Single Box",
    59: "Single Box, Open",
    60: "Fence Wall",
    61: "Fence Box",
    62: "Stairs",
    63: "Wall",
    64: "Wall, Double",
    65: "Wall, Corner",
    66: "Bridge",
    67: "Sign A",
    68: "Sign B",
    69: "Door, Small",
    70: "Door, Medium",
    71: "Door, Large",
    72: "Roadblock",
    73: "Soccer Ball",
    74: "Street Cone",
    75: "Forklift",
    76: "Cart, Electric",
    77: "Dinghy",
    78: "Fusion Coil",
    79: "Pallet",
    80: "Grav Lift",
    81: "Cannon, Man",
    82: "Shield Door, Large",
    83: "Shield Door",
    84: "Weapon Holder",
    85: "Blue Light",
    86: "Red Light",
    87: "FX, Nova",
    88: "FX, Pen And Ink",
    89: "FX, Olde Timey",
    90: "FX, Colorblind",
    91: "FX, Gloomy",
    92: "FX, Juicy",

    # MV Teleporter Pallette
    93: "Sender Node",
    94: "Receiver Node",
    95: "Two-Way Node",

    # MV Goals Pallette
    96: "CTF Spawn Point",
    97: "Respawn Point",
    98: "CTF Return Area",
    99: "Assault Spawn Point",
    100: "Assault Goal Area",
    101: "Juggernaut Destination Static",
    102: "Hill Static",
    103: "Oddball Spawn Point",
    104: "Territory Static",
    105: "VIP Destination Static",

    # MV Spawners Pallette
    106: "Assault Initial Spawn Point",
    107: "CTF Initial Spawn Point",
    108: "Hill Initial Spawn Point",
    109: "Oddball Initial Spawn Point",
    110: "Slayer Initial Spawn Point",
    111: "Territories Initial Spawn Point",
    112: "VIP Initial Spawn Point",
    113: "Assault Respawn Zone",
    114: "CTF Respawn Zone",
    115: "CTF Flag At Home Respawn Zone",
    116: "CTF Flag Away Respawn Zone",
    117: "Hill Respawn Zone",
    118: "Oddball Respawn Zone",
    119: "Slayer Respawn Zone",
    120: "Slayer Respawn Zone",
    121: "Territories Respawn Zone",
    122: "VIP Respawn Zone",
    123: "Infection Initial Spawn Point",
    # 124: "Infection Respawn Zone",

    124: "Respawn Point Invisible",
    125: "box_l",
    126: "box_m",
    127: "box_xl",
    128: "box_xxl",
    129: "box_xxxl",
    130: "wall_l",
    131: "wall_m",
    132: "wall_xl",
    133: "wall_xxl",
    134: "wall_xxxl",

}
