# Guardian Item List

guardianItems = {
    # MV Vehicle Pallette
    0: "Mongoose",

    # MV Weapon Pallette
    1: "Assault Rifle",
    2: "Battle Rifle",
    3: "Shotgun",
    4: "Sniper Rifle",
    5: "SMG",
    6: "Spiker",
    7: "Magnum",
    8: "Plasma Pistol",
    9: "Plasma Rifle",
    10: "Needler",
    11: "Brute Shot",
    12: "Rocket Launcher",
    13: "Spartan Laser",
    14: "Energy Sword",
    15: "Plasma Cannon",
    16: "Gravity Hammer",
    17: "Mauler",
    18: "Carbine",
    19: "Machine Gun Turret",
    20: "Flamethrower",
    21: "Fuel Rod Gun",
    22: "Beam Rifle",
    23: "Sentinel Beam",
    24: "Silenced SMG",
    25: "Automag",
    26: "Brute Plasma Rifle",
    27: "Missile Pod",
    28: "7-Wood",

    # MV Equipment Pallette
    29: "Frag Grenade",
    30: "Plasma Grenade",
    31: "Spike Grenade",
    32: "Firebomb Grenade",
    33: "Bubble Shield",
    34: "Power Drain",
    35: "Trip Mine",
    36: "Grav Lift",
    37: "Regenerator",
    38: "Radar Jammer",
    39: "Flare",
    40: "Deployable Cover",
    41: "Overshields",
    42: "Active Camo",
    43: "Custom Powerup",
    44: "Auto-Turret",
    45: "Invincibility",
    46: "Cloaking",

    # MV Scenery Pallette
    47: "Radio Set",
    48: "Rucksack",
    49: "Drum, 55 Gal",
    50: "Camping Stool",
    51: "Crate, Single",
    52: "Crate",
    53: "Barrel",
    54: "Barrel, Small",
    55: "Pallet",
    56: "Roadblock",
    57: "Street Cone",
    58: "Plasma Battery",
    59: "Power Core",
    60: "Turret Case",
    61: "Generator, Small",
    62: "Weapon Holder",
    63: "Grav Lift",

    # MV Teleporter Pallette
    64: "Sender Node",
    65: "Receiver Node",
    66: "Two-Way Node",

    # MV Goals Pallette
    67: "CTF Spoawn Point",
    68: "CTF Return Area",
    69: "Assault Spawn Point",
    70: "Assault Goal Area",
    71: "Juggernaut Destination Static",
    72: "Hill Static",
    73: "Oddball Spawn Point",
    74: "Territory Static",
    75: "VIP Destination Static",

    # MV Spawners Pallette
    76: "Respawn Point",
    77: "Assault Initial Spawn Point",
    78: "CTF Initial Spawn Point",
    79: "Hill Initial Spawn Point",
    80: "Oddball Initial Spawn Point",
    81: "Slayer Initial Spawn Point",
    82: "Territories Initial Spawn Point",
    83: "VIP Initial Spawn Point",
    84: "Assault Respawn Zone",
    85: "CTF Respawn Zone",
    86: "CTF Flag At Home Respawn Zone",
    87: "CTF Flag Away Respawn Zone",
    88: "Hill Respawn Zone",
    89: "Oddball Respawn Zone",
    90: "Slayer Respawn Zone",
    91: "Territories Respawn Zone",
    92: "VIP Respawn Zone",
    93: "Infection Initial Spawn Point",
    94: "Infection Respawn Zone"

}
