# Longshore Item List

longshoreItems = {
    0: "Ghost",
    1: "Mongoose",
    2: "Warthog",
    3: "Warthog. Gauss",
   

    4: "Energy Sword",
    5: "Magnum",
    6: "Needler",
    7: "Plasma Pistol",
    8: "Assault Rifle",
    9: "Battle Rifle",
    10: "Carbine",
    11: "Shotgun",
    12: "SMG",
    13: "Sniper Rifle",
    14: "Spiker",
    15: "Rocket Launcher",
    16: "Spartan Laser",
    17: "Brute shot",
    18: "Machinegun Turret",
    19: "Plasma Cannon",
    20: "Gravity Hammer",
    21: "Fuel Rod Gun",
    22: "Mauler",
    23: "Flamethrower",
    24: "Beam Rifle",
    25: "Sentinel Beam",
    26: "Missile Pod",
    27: "Plasma Rifle",
    28: "Silenced SMG",
    29: "Automag",
    30: "Brute Plasma Rifle",
    31: "7-Wood",

    32: "Frag Grenade",
    33: "Plasma Grenade",
    34: "Spike Grenade",
    35: "Firebomb Grenade",
    36: "Bubble Shield",
    37: "Power Drain",
    38: "Trip Mine",
    39: "Grav Lift",
    40: "Regenerator",
    41: "Radar Jammer",
    42: "Flare",
    43: "Deployable Cover",
    44: "Overshields",
    45: "Active Camo",
    46: "Custom Powerup",
    47: "Auto-Turret",
    48: "Invincibility",
    49: "Cloaking",

    # MAP VARIANT SCENERY STARTS
    50: "Fusion Coil",
    51: "Crate, Fish",
    52: "Double Box, Open",
    53: "Double Box",
    54: "Single Box",
    55: "Single Box, Open",
    56: "Palette, Fish",
    57: "Dinghy",
    58: "Forklift",
    59: "Street Cone",
    60: "Water Crate",
    61: "Water Barrel",
    62: "Pallet",
    63: "Door, Small",
    64: "Door, Medium",
    65: "Door, Large",
    66: "Propane Tank",
    67: "Weapon Holder",
    68: "Grav Lift",
    69: "Shield Door, Large",
    70: "Shield Door",
    71: "Cannon, Man",
    72: "Soccer Ball",
    73: "FX, Nova",
    74: "FX, Pen And Ink",
    75: "FX, Olde Timey",
    76: "FX, Colorblind",
    77: "FX, Gloomy",
    78: "FX, Juicy",
    

    # MAP VARIANT TELEPORTERS START
    79: "Sender Node",
    80: "Receiver Node",
    81: "Two-Way Node",
    # MAP VARIANT TELEPORTERS END

    # MAP VARIANT SPAWNERS START
    82: "Respawn Point",
    83: "CTF Flag Spawn Point",
    84: "CTF Flag Return Area",
    85: "Assault Bomb Spawn Point",
    86: "Assault Bomb Goal Area",
    87: "Juggernaut Destination Static",
    88: "Hill Static",
    89: "Oddball Spawn Point",
    90: "Territory Static",
    91: "VIP Destination Static",


    92: "Assault Initial Spawn Point",
    93: "CTF Initial Spawn Point",
    94: "Hill Initial Spawn Point",
    95: "Oddball Initial Spawn Point",
    96: "Slayer Initial Spawn Point",
    97: "Territories Initial Spawn Point",
    98: "VIP Initial Spawn Point",
    99: "Assault Respawn Zone",
    100: "CTF Respawn Zone",
    101: "CTF Flag At Home Respawn Zone",
    102: "CTF Flag Away Respawn Zone",
    103: "Hill Respawn Zone",
    104: "Oddball Respawn Zone",
    105: "Slayer Respawn Zone",
    106: "Territories Respawn Zone",
    107: "VIP Respawn Zone",
    108: "Infection Initial Spawn Point",
    109: "Infection Respawn Zone",

    110: "Security Camera",
    111: "Skull",
    112: "Respawn Point Invisible",
    113: "box_l",
    114: "box_m",
    115: "box_xl",
    116: "box_xxl",
    117: "box_xxxl",
    118: "wall_l",
    119: "wall_m",
    120: "wall_xl",
    121: "wall_xxl",
    122: "wall_xxxl",
}
