# Standoff Item List

standoffItems = {
    0: "Ghost",
    1: "Mongoose",
    2: "Warthog",
    3: "Chopper",
    4: "Banshee",
    5: "Wraith",
    6: "Warthog, Gauss",
   

    7: "Energy Sword",
    8: "Magnum",
    9: "Needler",
    10: "Plasma Pistol",
    11: "Assault Rifle",
    12: "Battle Rifle",
    13: "Carbine",
    14: "Shotgun",
    15: "SMG",
    16: "Sniper Rifle",
    17: "Spiker",
    18: "Rocket Launcher",
    19: "Spartan Laser",
    20: "Brute Shot",
    21: "Machinegun Turret",
    22: "Plasma Cannon",
    23: "Gravity Hammer",
    24: "Fuel Rod Gun",
    25: "Mauler",
    26: "Flamethrower",
    27: "Beam Rifle",
    28: "Sentinel Beam",
    29: "Missile Pod",
    30: "Plasma Rifle",
    31: "Silenced SMG",
    32: "Automag",
    33: "Brute Plasma Rifle",
    34: "Plasma Cannon",
    35: "7-Wood",

    36: "Frag Grenade",
    37: "Plasma Grenade",
    38: "Spike Grenade",
    39: "Firebomb Grenade",
    40: "Bubble Shield",
    41: "Power Drain",
    42: "Trip Mine",
    43: "Grav Lift",
    44: "Regenerator",
    45: "Radar Jammer",
    46: "Flare",
    47: "Deployable Cover",
    48: "Overshields",
    49: "Active Camo",
    50: "Custom Powerup",
    51: "Auto-Turret",
    52: "Invincibility",
    53: "Cloaking",

    # MAP VARIANT SCENERY STARTS
    54: "Fusion Coil",
    55: "Crate",
    56: "Barrel",
    57: "Barrel, Small",
    58: "Crate, Single",
    59: "Camping Stool",
    60: "Radio Antennae",
    61: "Fence Box",
    62: "Drum, 12 Gal",
    63: "Drum, 55 Gal",
    64: "Generator, Small",
    65: "Radio Set",
    66: "Pallet",
    67: "Roadblock",
    68: "Street Cone",
    69: "Barrier",
    70: "Barrier, Short",
    71: "Barricade",
    72: "Propane Tank",
    73: "Missile, Body",
    74: "Forklift",
    75: "Wire Spool",
    76: "Double Box, Open",
    77: "Bridge",
    78: "Weapon Holder",
    79: "Grav Lift",
    80: "Shield Door, Large",
    81: "Shield Door",
    82: "Cannon, Man",
    83: "Soccer Ball",
    

    # MAP VARIANT TELEPORTERS START
    84: "Sender Node",
    85: "Receiver Node",
    86: "Two-Way Node",
    # MAP VARIANT TELEPORTERS END

    # MAP VARIANT SPAWNERS START
    87: "Respawn Point",
    88: "CTF Flag Spawn Point",
    89: "CTF Flag Return Area",
    90: "Assault Bomb Spawn Point",
    91: "Assault Bomb Goal Area",
    92: "Juggernaut Destination Static",
    93: "Hill Static",
    94: "Oddball Spawn Point",
    95: "Territory Static",
    96: "VIP Destination Static",


    97: "Assault Initial Spawn Point",
    98: "CTF Initial Spawn Point",
    99: "Hill Initial Spawn Point",
    100: "Oddball Initial Spawn Point",
    101: "Slayer Initial Spawn Point",
    102: "Territories Initial Spawn Point",
    103: "VIP Initial Spawn Point",
    104: "Assault Respawn Zone",
    105: "CTF Respawn Zone",
    106: "CTF Flag At Home Respawn Zone",
    107: "CTF Flag Away Respawn Zone",
    108: "Hill Respawn Zone",
    109: "Oddball Respawn Zone",
    110: "Slayer Respawn Zone",
    111: "Territories Respawn Zone",
    112: "VIP Respawn Zone",
    113: "Infection Initial Spawn Point",
    114: "Infection Respawn Zone",

    115: "Respawn Point Invisible",
    116: "box_l",
    117: "box_m",
    118: "box_xl",
    119: "box_xxl",
    120: "box_xxxl",
    121: "wall_l",
    122: "wall_m",
    123: "wall_xl",
    124: "wall_xxl",
    125: "wall_xxxl"
}
