# Orbital Item List

orbitalItems = {
    # MV Vehicle Pallette
    0: "Ghost",
    1: "Mongoose",

    # MV Weapon Pallette
    2: "Energy Sword",
    3: "Magnum",
    4: "Needler",
    5: "Plasma Pistol",
    6: "Assault Rifle",
    7: "Battle Rifle",
    8: "Carbine",
    9: "Shotgun",
    10: "SMG",
    11: "Sniper Rifle",
    12: "Spiker",
    13: "Rocket Launcher",
    14: "Spartan Laser",
    15: "Brute shot",
    16: "Machinegun Turret",
    17: "Plasma Cannon",
    18: "Gravity Hammer",
    19: "Plasma Rifle",
    20: "Fuel Rod Gun",
    21: "Mauler",
    22: "Flamethrower",
    23: "Beam Rifle",
    24: "Sentinel Beam",
    25: "Missile Pod",
    26: "Silenced SMG",
    27: "Automag",
    28: "Brute Plasma Rifle",
    29: "7-Wood",
   
   # MV Equipment Pallette
    30: "Frag Grenade",
    31: "Plasma Grenade",
    32: "Spike Grenade",
    33: "Firebomb Grenade",
    34: "Bubble Shield",
    35: "Power Drain",
    36: "Trip Mine",
    37: "Grav Lift",
    38: "Regenerator",
    39: "Radar Jammer",
    40: "Flare",
    41: "Deployable Cover",
    42: "Overshields",
    43: "Active Camo",
    44: "Custom Powerup",
    45: "Auto-Turret",
    46: "Invincibility",
    47: "Cloaking",

    # MV Scenery Pallette
    48: "Supply Case",
    49: "Fusion Coil",
    50: "Cardboard Box, Medium",
    51: "Cardboard Box, Small",
    52: "Space Trashcan",
    53: "Street Cone",
    54: "Toolbox",
    55: "Toolbox, Small",
    56: "Pallet",
    57: "Propane Tank",
    58: "Wire Spool",
    59: "Server",
    60: "Generator",
    61: "Door",
    62: "Weapon Holder",
    63: "Grav Lift",
    64: "Shield Door",
    65: "Cannon, Man",
    66: "Soccer Ball",
    67: "FX, Nova",
    68: "FX, Pen And Ink",
    69: "FX, Olde Timey",
    70: "FX, Colorblind",
    71: "FX, Gloomy",
    72: "FX, Juicy",
    

    # MV Teleporters Pallette
    73: "Sender Node",
    74: "Receiver Node",
    75: "Two-Way Node",

    # MV Goals Pallette
    76: "CTF Flag Spawn Point",
    77: "CTF Flag Return Area",
    78: "Assault Bomb Spawn Point",
    79: "Assault Bomb Goal Area",
    80: "Juggernaut Destination Static",
    81: "Hill Static",
    82: "Oddball Spawn Point",
    83: "Territory Static",
    84: "VIP Destination Static",


    # MV Spawners Pallette
    85: "Respawn Point",
    86: "Assault Initial Spawn Point",
    87: "CTF Initial Spawn Point",
    88: "Hill Initial Spawn Point",
    89: "Oddball Initial Spawn Point",
    90: "Slayer Initial Spawn Point",
    91: "Territories Initial Spawn Point",
    92: "VIP Initial Spawn Point",
    93: "Assault Respawn Zone",
    94: "CTF Respawn Zone",
    95: "CTF Flag At Home Respawn Zone",
    96: "CTF Flag Away Respawn Zone",
    97: "Hill Respawn Zone",
    98: "Oddball Respawn Zone",
    99: "Slayer Respawn Zone",
    100: "Territories Respawn Zone",
    101: "VIP Respawn Zone",
    102: "Infection Initial Spawn Point",
    103: "Infection Respawn Zone"
}
