# Heretic Item List

hereticItems = {
    # MV Vehicle Pallette
    0: "Ghost",
    1: "Mongoose",

    # MV Weapon Pallette
    2: "Assault Rifle",
    3: "Battle Rifle",
    4: "Beam Rifle",
    5: "Brute Shot",
    6: "Carbine",
    7: "Energy Sword",
    8: "Flamethrower",
    9: "Fuel Rod Gun",
    10: "Gravity Hammer",
    11: "Machine Gun Turret",
    12: "Magnum",
    13: "Mauler",
    14: "Needler",
    15: "Plasma Cannon",
    16: "Plasma Pistol",
    17: "Plasma Rifle",
    18: "Rocket Launcher",
    19: "Shotgun",
    20: "SMG",
    21: "Sniper Rifle",
    22: "Spartan Laser",
    23: "Spiker",
    24: "Sentinel Beam",
    25: "Silenced SMG",
    26: "Automag",
    27: "Brute Plasma Rifle",
    28: "Missile Pod",
    29: "7-Wood",
   
   # MV Equipment Pallette
    30: "Frag Grenade",
    31: "Plasma Grenade",
    32: "Spike Grenade",
    33: "Firebomb Grenade",
    34: "Bubble Shield",
    35: "Power Drain",
    36: "Trip Mine",
    37: "Grav Lift",
    38: "Regenerator",
    39: "Radar Jammer",
    40: "Flare",
    41: "Deployable Cover",
    42: "Overshields",
    43: "Active Camo",
    44: "Custom Powerup",
    45: "Auto-Turret",
    46: "Invincibility",
    47: "Cloaking",

    # MV Scenery Pallette
    48: "Barrier",
    49: "Camping Stool",
    50: "Comm Node",
    51: "Plasma Battery",
    52: "Supply Case, Open",
    53: "Supply Case",
    54: "Weapon Holder",
    55: "Grav Lift",
    56: "Shield Door, Large",
    57: "Shield Door",
    58: "Cannon, Man",
    59: "Soccer Ball",
    60: "FX, Nova",
    61: "FX, Pen And Ink",
    62: "FX, Olde Timey",
    63: "FX, Colorblind",
    64: "FX, Gloomy",
    65: "FX, Juicy",
    

    # MV Teleporters Pallette
    66: "Sender Node",
    67: "Receiver Node",
    68: "Two-Way Node",

    # MV Goals Pallette
    69: "Assault Goal Area",
    70: "Assault Spawn Point",
    71: "CTF Return Area",
    72: "CTF Spawn Point",
    73: "Juggernaut Destination Static",
    74: "Hill Static",
    75: "Oddball Spawn Point",
    76: "Territory Static",
    77: "VIP Destination Static",


    # MV Spawners Pallette
    78: "Respawn Point",
    79: "Assault Initial Spawn Point",
    80: "CTF Initial Spawn Point",
    81: "Hill Initial Spawn Point",
    82: "Oddball Initial Spawn Point",
    83: "Slayer Initial Spawn Point",
    84: "Territories Initial Spawn Point",
    85: "VIP Initial Spawn Point",
    86: "Assault Respawn Zone",
    87: "CTF Respawn Zone",
    88: "CTF Flag At Home Respawn Zone",
    89: "CTF Flag Away Respawn Zone",
    90: "Hill Respawn Zone",
    91: "Oddball Respawn Zone",
    92: "Slayer Respawn Zone",
    93: "Territories Respawn Zone",
    94: "VIP Respawn Zone",
    95: "Infection Initial Spawn Point",
    96: "Infection Respawn Zone"
}
