# Longshore Item List

longshoreItems = {
    0: "Ghost",
    1: "Mongoose",
    2: "Warthog",
    3: "Warthog. Gauss",
   

    8: "Energy Sword",
    9: "Magnum",
    10: "Needler",
    11: "Plasma Pistol",
    12: "Assault Rifle",
    13: "Battle Rifle",
    14: "Carbine",
    15: "Shotgun",
    16: "SMG",
    17: "Sniper Rifle",
    18: "Spiker",
    19: "Rocket Launcher",
    20: "Spartan Laser",
    21: "Brute shot",
    22: "Machinegun Turret",
    23: "Plasma Cannon",
    24: "Gravity Hammer",
    25: "Fuel Rod Gun",
    26: "Mauler",
    27: "Flamethrower",
    28: "Beam Rifle",
    29: "Sentinel Beam",
    30: "Missile Pod",
    31: "Plasma Rifle",
    32: "Silenced SMG",
    33: "Automag",
    34: "Brute Plasma Rifle",
    35: "7-Wood",

    36: "Frag Grenade",
    37: "Plasma Grenade",
    38: "Spike Grenade",
    39: "Firebomb Grenade",
    40: "Bubble Shield",
    41: "Power Drain",
    42: "Trip Mine",
    43: "Grav Lift",
    44: "Regenerator",
    45: "Radar Jammer",
    46: "Flare",
    47: "Deployable Cover",
    48: "Overshields",
    49: "Active Camo",
    50: "Custom Powerup",
    51: "Auto-Turret",
    52: "Invincibility",
    53: "Cloaking",

    # MAP VARIANT SCENERY STARTS
    56: "Fusion Coil",
    57: "Crate, Fish",
    58: "Double Box, Open",
    59: "Double Box",
    60: "Single Box",
    61: "Single Box, Open",
    62: "Palette, Fish",
    63: "Dinghy",
    64: "Forklift",
    65: "Street Cone",
    66: "Water Crate",
    67: "Water Barrel",
    68: "Pallet",
    69: "Door, Small",
    70: "Door, Medium",
    71: "Door, Large",
    72: "Propane Tank",
    73: "Weapon Holder",
    74: "Grav Lift",
    75: "Shield Door, Large",
    76: "Shield Door",
    77: "Cannon, Man",
    78: "Soccer Ball",
    79: "FX, Nova",
    80: "FX, Pen And Ink",
    81: "FX, Olde Timey",
    82: "FX, Colorblind",
    83: "FX, Gloomy",
    84: "FX, Juicy",
    

    # MAP VARIANT TELEPORTERS START
    85: "Sender Node",
    86: "Receiver Node",
    87: "Two-Way Node",
    # MAP VARIANT TELEPORTERS END

    # MAP VARIANT SPAWNERS START
    89: "CTF Flag Spawn Point",
    90: "CTF Flag Return Area",
    91: "Assault Bomb Spawn Point",
    92: "Assault Bomb Goal Area",
    93: "Juggernaut Destination Static",
    94: "Hill Static",
    95: "Oddball Spawn Point",
    96: "Territory Static",
    97: "VIP Destination Static",


    98: "Respawn Point",
    99: "Assault Initial Spawn Point",
    100: "CTF Initial Spawn Point",
    101: "Hill Initial Spawn Point",
    102: "Oddball Initial Spawn Point",
    103: "Slayer Initial Spawn Point",
    104: "Territories Initial Spawn Point",
    105: "VIP Initial Spawn Point",
    106: "Assault Respawn Zone",
    107: "CTF Respawn Zone",
    108: "CTF Flag At Home Respawn Zone",
    109: "CTF Flag Away Respawn Zone",
    110: "Hill Respawn Zone",
    111: "Oddball Respawn Zone",
    112: "Slayer Respawn Zone",
    113: "Territories Respawn Zone",
    114: "VIP Respawn Zone",
    115: "Infection Initial Spawn Point",
    116: "Infection Respawn Zone"
}
