# Citadel Item List

citadelItems = {
    # MV Vehicle Pallette
    0: "Ghost",
    1: "Mongoose",

    # MV Weapon Pallette
    2: "Energy Sword",
    3: "Magnum",
    4: "Needler",
    5: "Plasma Pistol",
    6: "Assault Rifle",
    7: "Battle Rifle",
    8: "Carbine",
    9: "Shotgun",
    10: "SMG",
    11: "Sniper Rifle",
    12: "Spiker",
    13: "Rocket Launcher",
    14: "Spartan Laser",
    15: "Brute shot",
    16: "Machinegun Turret",
    17: "Plasma Cannon",
    18: "Gravity Hammer",
    19: "Fuel Rod Gun",
    20: "Mauler",
    21: "Plasma Rifle",
    22: "Flamethrower",
    23: "Beam Rifle",
    24: "Sentinel Beam",
    25: "Missile Pod",
    26: "Silenced SMG",
    27: "Automag",
    28: "Brute Plasma Rifle",
    29: "7-Wood",
   
   # MV Equipment Pallette
    30: "Frag Grenade",
    31: "Plasma Grenade",
    32: "Spike Grenade",
    33: "Firebomb Grenade",
    34: "Bubble Shield",
    35: "Power Drain",
    36: "Trip Mine",
    37: "Grav Lift",
    38: "Regenerator",
    39: "Radar Jammer",
    40: "Flare",
    41: "Deployable Cover",
    42: "Overshields",
    43: "Active Camo",
    44: "Custom Powerup",
    45: "Auto-Turret",
    46: "Invincibility",
    47: "Cloaking",

    # MV Scenery Pallette
    48: "Plasma Battery",
    49: "Power Core",
    50: "Energy Blocker, Large",
    51: "Energy Blocker, Small",
    52: "Barricade",
    53: "Wall",
    54: "Barrier",
    55: "Wall, Corner",
    56: "Forerunner Crate, Blue",
    57: "Forerunner Crate, Red",
    58: "Weapon Holder",
    59: "Grav Lift",
    60: "Shield Door, Large",
    61: "Shield Door",
    62: "Cannon, Man",
    63: "Soccer Ball",
    64: "FX, Nova",
    65: "FX, Pen And Ink",
    66: "FX, Olde Timey",
    67: "FX, Colorblind",
    68: "FX, Gloomy",
    69: "FX, Juicy",
    

    # MV Teleporters Pallette
    70: "Sender Node",
    71: "Receiver Node",
    72: "Two-Way Node",

    # MV Goals Pallette
    73: "Respawn Point",
    74: "CTF Flag Spawn Point",
    75: "CTF Flag Return Area",
    76: "Assault Bomb Spawn Point",
    77: "Assault Bomb Goal Area",
    78: "Juggernaut Destination Static",
    79: "Hill Static",
    80: "Oddball Spawn Point",
    81: "Territory Static",
    82: "VIP Destination Static",


    # MV Spawners Pallette
    83: "Assault Initial Spawn Point",
    84: "CTF Initial Spawn Point",
    85: "Hill Initial Spawn Point",
    86: "Oddball Initial Spawn Point",
    87: "Slayer Initial Spawn Point",
    88: "Territories Initial Spawn Point",
    89: "VIP Initial Spawn Point",
    90: "Assault Respawn Zone",
    91: "CTF Respawn Zone",
    92: "CTF Flag At Home Respawn Zone",
    93: "CTF Flag Away Respawn Zone",
    94: "Hill Respawn Zone",
    95: "Oddball Respawn Zone",
    96: "Slayer Respawn Zone",
    97: "Territories Respawn Zone",
    98: "VIP Respawn Zone",
    99: "Infection Initial Spawn Point",
    100: "Infection Respawn Zone",

    103: "box_l",
    104: "box_m",
    105: "box_xl",
    106: "box_xxl",
    107: "box_xxxl",
    108: "wall_l",
    109: "wall_m",
    110: "wall_xl",
    111: "wall_xxl",
    112: "wall_xxxl",
}
