# Sandbox Item List

sandboxItems = {
    0: "Banshee",
    1: "Chopper",
    2: "Hornet",
    3: "Ghost",
    4: "Prowler",
    5: "Mongoose",
    6: "Scorpion",
    7: "Warthog",
    8: "Warthog, Gauss",
    9: "Wraith",

    16: "Assault Rifle",
    17: "Battle Rifle",
    18: "Shotgun",
    19: "Sniper Rifle",
    20: "SMG",
    21: "Spiker",
    22: "Magnum",
    23: "Plasma Pistol",
    24: "Plasma Rifle",
    25: "Needler",
    26: "Brute Shot",
    27: "Rocket Launcher",
    28: "Spartan Laser",
    29: "Energy Sword",
    30: "Plasma Cannon",
    31: "Gravity Hammer",
    32: "Covenant Carbine",
    33: "Mauler",
    34: "Fuel Rod Gun",
    35: "Beam Rifle",
    36: "Sentinel Beam",
    37: "Machine Gun Turret",
    38: "Flamethrower",
    39: "Missile Pod",

    43: "Frag Grenade",
    44: "Plasma Grenade",
    45: "Spike Grenade",
    46: "Firebomb Grenade",
    47: "Bubble Shield",
    48: "Power Drain",
    49: "Trip Mine",
    50: "Grav Lift",
    51: "Regenerator",
    52: "Radar Jammer",
    53: "Flare",
    54: "Deployable Cover",
    55: "Overshield",
    56: "Active Camo",
    57: "Custom Powerup",
    58: "Auto-Turret",
    59: "SPNKR Ammo",

    # MAP VARIANT SCENERY STARTS
    62: "Wall",
    63: "Wall, Half",
    64: "Wall, Quarter",
    65: "Wall, Corner",
    66: "Wall, Slit",
    67: "Wall, T",
    68: "Wall, Double",
    69: "Wedge, Small",
    70: "Wedge, Long",
    71: "Block, Large",
    72: "Block, Double",
    73: "Block, Tall",
    74: "Block, Huge",
    75: "Wedge, Huge",
    76: "Ramp, Long",
    77: "Wedge, Large",
    78: "Wedge, Corner",
    79: "Tube Piece",
    80: "Tube Y-Intersection",
    81: "Tube, Corner",
    82: "Tube Ramp",
    83: "Column, Stone Small",
    84: "Column, Damaged Small",
    85: "Column, Blue Small",
    86: "Column, Red Small",
    87: "Column, Large",
    88: "Column, Stone Large",
    89: "Block, Tiny",
    90: "Block, Small",
    91: "Block, Flat",
    92: "Block, Angled",
    93: "Corner, Small",
    94: "Corner, Large",
    95: "Stone Bridge",
    96: "Obelisk",
    97: "Fin",
    98: "Ramp, Short",
    99: "Ramp, Wide",
    100: "Ramp, Thick",
    101: "Stone Platform",
    102: "Arch",
    103: "Weapon Holder",
    104: "Wood Bridge, Large",
    105: "Wood Bridge, Thin",
    106: "Barricade",
    108: "Fusion Coil",
    109: "Pallet",
    110: "Frav Lift",
    111: "Mancannon",
    112: "Shield Door",
    114: "FX, Nova",
    115: "FX, Pen And Ink",
    116: "FX, Old Timey",
    117: "FX, Gloomy",
    118: "FX, Colorblind",
    119: "FX, Juicy",
    120: "Light, Blue",
    121: "Light, Red",
    122: "Killball",
    123: "7-Wood",
    124: "Tin Cup",
    125: "Golf Ball",
    126: "Wall, Corner, Short",
    127: "Steel Ramp",
    128: "Steel Wall",
    129: "Steel Barrier",
    130: "Stell Wall, Corner",
    131: "Watchtower Base",
    132: "Forerunner Crate, Blue",
    133: "Forerunner Crate, Red",
    134: "Comm Node",
    135: "Supply Case",
    136: "Supply Case, Open",
    137: "Barricade, Covenant",
    138: "Tube Shield",
    139: "Forklift",
    140: "Dinghy",
    141: "Soccer Ball",
    142: "Ramp, Covenant",
    143: "Door, Small",
    144: "Door, Medium",
    145: "Door, Large",
    146: "Door",
    157: "Radio Antennae",
    # MAP VARIANT SCENERY ENDS

    # MAP VARIANT TELEPORTERS START
    147: "Teleporter Sender",
    148: "Teleporter Receiver",
    149: "Teleporter 2-way",
    # MAP VARIANT TELEPORTERS END

    # MAP VARIANT SPAWNERS START
    150: "Respawn Point",
    151: "Assault Initial Spawn Point",
    152: "CTF Initial Spawn Point",
    153: "KOTH Initial Spawn Point",
    154: "Oddball Initial Spawn Point",
    155: "Slayer Initial Spawn Point",
    156: "Territories Initial Spawn Point",
    157: "VIP Initial Spawn Point",
    158: "Assault Respawn Zone",
    159: "CTF Respawn Zone",
    160: "CTF Flag at Home Respawn Zone",
    161: "CTF Flag Away Respawn Zone",
    162: "KOTH Respawn Zone",
    163: "Oddball Respawn Zone",
    164: "Slayer Respawn Zone",
    165: "Territories Respawn Zone",
    166: "VIP Respawn Zone",
    167: "Infection Respawn Zone",
    168: "Spawn Point",
    169: "Spawn Point Invisible",
    # MAP VARIANT SPAWNERS END

    # MAP VARIANT GOALS START
    170: "Flag Spawn Point",
    171: "Flag Return Point",
    172: "Assault Bomb Spawn Point",
    173: "Assault Bomb Goal Area",
    174: "Hill Marker",
    175: "Ball Spawn Point",
    176: "Obelisk Eyeball",
    177: "VIP Destination Static",
    # MAP VARIANT GOALS END

    # SCENERY START
    178: "Skull",
    179: "Grid Hidden",
    180: "Spawn Point Invisible",
    181: "Teleporter 2-way Sandbox",
    182: "box_l",
    183: "box_m",
    184: "box_xl",
    185: "box_xxl",
    186: "box_xxxl",
    187: "wall_l",
    188: "wall_m",
    189: "wall_xl",
    190: "wall_xxl",
    191: "wall_xxxl"
}