# Coldstorage Item List

coldstorageItems = {
    # MV Vehicle Pallette
    0: "Ghost",
    1: "Mongoose",

    # MV Weapon Pallette
    2: "Energy Sword",
    3: "Magnum",
    4: "Needler",
    5: "Plasma Pistol",
    6: "Assault Rifle",
    7: "Battle Rifle",
    8: "Carbine",
    9: "Shotgun",
    10: "SMG",
    11: "Sniper Rifle",
    12: "Spiker",
    13: "Rocket Launcher",
    14: "Spartan Laser",
    15: "Brute shot",
    16: "Machinegun Turret",
    17: "Plasma Cannon",
    18: "Gravity Hammer",
    19: "Fuel Rod Gun",
    20: "Mauler",
    21: "Flamethrower",
    22: "Beam Rifle",
    23: "Sentinel Beam",
    24: "Missile Pod",
    25: "Silenced SMG",
    26: "Automag",
    27: "Brute Plasma Rifle",
    28: "7-Wood",
   
   # MV Equipment Pallette
    29: "Frag Grenade",
    30: "Plasma Grenade",
    31: "Spike Grenade",
    32: "Firebomb Grenade",
    33: "Bubble Shield",
    34: "Power Drain",
    35: "Trip Mine",
    36: "Grav Lift",
    37: "Regenerator",
    38: "Radar Jammer",
    39: "Flare",
    40: "Deployable Cover",
    41: "Overshields",
    42: "Active Camo",
    43: "Custom Powerup",
    44: "Auto-Turret",
    45: "Invincibility",
    46: "Cloaking",

    # MV Scenery Pallette
    47: "Fusion Coil",
    48: "Power Core",
    49: "Barricade",
    50: "Wall",
    51: "Barrier",
    52: "Wall, Corner",
    53: "Energy Blocker, Large",
    54: "Energy Blocker, Small",
    55: "Energy Blocker, Tiny",
    56: "Weapon Holder",
    57: "Grav Lift",
    58: "Shield Door",
    59: "Cannon, Man",
    60: "Soccer Ball",
    61: "FX, Nova",
    62: "FX, Pen And Ink",
    63: "FX, Olde Timey",
    64: "FX, Colorblind",
    65: "FX, Gloomy",
    66: "FX, Juicy",
    

    # MV Teleporters Pallette
    67: "Sender Node",
    68: "Receiver Node",
    69: "Two-Way Node",

    # MV Goals Pallette
    70: "CTF Flag Spawn Point",
    71: "CTF Flag Return Area",
    72: "Assault Bomb Spawn Point",
    73: "Assault Bomb Goal Area",
    74: "Juggernaut Destination Static",
    75: "Hill Static",
    76: "Oddball Spawn Point",
    77: "Territory Static",
    78: "VIP Destination Static",


    # MV Spawners Pallette
    79: "Respawn Point",
    80: "Assault Initial Spawn Point",
    81: "CTF Initial Spawn Point",
    82: "Hill Initial Spawn Point",
    83: "Oddball Initial Spawn Point",
    84: "Slayer Initial Spawn Point",
    85: "Territories Initial Spawn Point",
    86: "VIP Initial Spawn Point",
    87: "Assault Respawn Zone",
    88: "CTF Respawn Zone",
    89: "CTF Flag At Home Respawn Zone",
    90: "CTF Flag Away Respawn Zone",
    91: "Hill Respawn Zone",
    92: "Oddball Respawn Zone",
    93: "Slayer Respawn Zone",
    94: "Territories Respawn Zone",
    95: "VIP Respawn Zone",
    96: "Infection Initial Spawn Point",
    97: "Infection Respawn Zone"
}
