# Highground Item List

highgroundItems = {
    # MV Vehicle Pallette
    0: "Ghost",
    1: "Mongoose",
    2: "Warthog",
    3: "Chopper",
    4: "Prowler",
    5: "Wraith",
    6: "Scorpion",
    7: "Warthog, Gauss",

    # MV Weapon Pallette
    8: "Energy Sword",
    9: "Magnum",
    10: "Needler",
    11: "Plasma Pistol",
    12: "Assault Rifle",
    13: "Battle Rifle",
    14: "Carbine",
    15: "Shotgun",
    16: "SMG",
    17: "Sniper Rifle",
    18: "Spiker",
    19: "Rocket Launcher",
    20: "Spartan Laser",
    21: "Brute shot",
    22: "Machinegun Turret",
    23: "Plasma Cannon",
    24: "Gravity Hammer",
    25: "Fuel Rod Gun",
    26: "Mauler",
    27: "Flamethrower",
    28: "Beam Rifle",
    29: "Sentinel Beam",
    30: "Plasma Rifle",
    31: "Silenced SMG",
    32: "Automag",
    33: "Brute Plasma Rifle",
    34: "Missile Pod",
    35: "7-Wood",

    # MV Equipment Pallette
    36: "Frag Grenade",
    37: "Plasma Grenade",
    38: "Spike Grenade",
    39: "Firebomb Grenade",
    40: "Bubble Shield",
    41: "Power Drain",
    42: "Trip Mine",
    43: "Grav Lift",
    44: "Regenerator",
    45: "Radar Jammer",
    46: "Flare",
    47: "Deployable Cover",
    48: "Overshields",
    49: "Active Camo",
    50: "Custom Powerup",
    51: "Auto-Turret",
    52: "Invincibility",
    53: "Cloaking",

    # MV Scenery Pallette
    54: "Fusion Coil",
    55: "Crate",
    56: "Barrel",
    57: "Barrel, Small",
    58: "Crate, Single",
    59: "Medical Cabinet", 
    60: "Camping Stool",
    61: "Turret Case, Lid",
    62: "Turret Case, Open",
    63: "Computer",
    64: "Computer, Small",
    65: "Medical Cart",
    66: "Drum, 12 Gal",
    67: "Drum, 55 Gal",
    68: "Floodlights",
    69: "Ammo Crate",
    70: "Radio Set",
    71: "Medical Crate",
    72: "Medical Tray",
    73: "Pallet",
    74: "Toolbox",
    75: "Toolbox, Small",
    76: "Roadblock",
    77: "Street Cone",
    78: "Barrier",
    79: "Barrier, Short",
    80: "Tire",
    81: "Telephone",
    82: "Propane Tank",
    83: "Weapon Holder",
    84: "Grav Lift",

    # MV Teleporter Pallette
    85: "Sender Node",
    86: "Receiver Node",
    87: "Two-Way Node",

    # MV Goals Pallette
    88: "CTF Spoawn Point",
    89: "CTF Return Area",
    90: "Assault Spawn Point",
    91: "Assault Goal Area",
    92: "Juggernaut Destination Static",
    93: "Hill Static",
    94: "Oddball Spawn Point",
    95: "Territory Static",
    96: "VIP Destination Static",

    # MV Spawners Pallette
    97: "Respawn Point",
    98: "Assault Initial Spawn Point",
    99: "CTF Initial Spawn Point",
    100: "Hill Initial Spawn Point",
    101: "Oddball Initial Spawn Point",
    102: "Slayer Initial Spawn Point",
    103: "Territories Initial Spawn Point",
    104: "VIP Initial Spawn Point",
    105: "Assault Respawn Zone",
    106: "CTF Respawn Zone",
    107: "CTF Flag At Home Respawn Zone",
    108: "CTF Flag Away Respawn Zone",
    109: "Hill Respawn Zone",
    110: "Oddball Respawn Zone",
    111: "Slayer Respawn Zone",
    112: "Territories Respawn Zone",
    113: "VIP Respawn Zone",
    114: "Infection Initial Spawn Point",
    115: "Infection Respawn Zone"
}
