# Avalanche Item List

avalancheItems = {
    0: "Warthog",
    1: "Mongoose",
    2: "Ghost",
    3: "Chopper",
    4: "Wraith",
    5: "Banshee",
    6: "Hornet, Transport",
    7: "Scorpion",
    8: "Prowler",
    9: "Elephant",
    10: "Wraith, Anti-Air",
    11: "Warthog, Transport",
    12: "Warthog, Wrecked",
    13: "Shade Turret",
    14: "Hornet",
    15: "Warthog, Gauss",

    16: "Assault Rifle",
    17: "Battle Rifle",
    18: "Shotgun",
    19: "Sniper Rifle",
    20: "SMG",
    21: "Spiker",
    22: "Magnum",
    23: "Plasma Pistol",
    24: "Needler",
    25: "Beam Rifle",
    26: "Brute Shot",
    27: "Rocket Launcher",
    28: "Spartan Laser",
    29: "Energy Sword",
    30: "Machine Gun Turret",
    31: "Gravity Hammer",
    32: "Missile Pod",
    33: "Sentinel Beam",
    34: "Flamethrower",
    35: "Fuel Rod Gun",
    36: "Plasma Cannon",
    37: "Carbine",
    38: "Mauler",
    39: "Plasma Rifle",
    40: "Silenced SMG",
    41: "Automag",
    42: "Brute Plasma Rifle",

    43: "Frag Grenade",
    44: "Plasma Grenade",
    45: "Spike Grenade",
    46: "Firebomb Grenade",
    47: "Bubble Shield",
    48: "Power Drain",
    49: "Trip Mine",
    50: "Grav Lift",
    51: "Regenerator",
    52: "Radar Jammer",
    53: "Flare",
    54: "Deployable Cover",
    55: "Overshields",
    56: "Active Camo",
    57: "Custom Powerup",
    58: "Auto-Turret",
    59: "SPNKR Ammo",
    60: "Invincibility",
    61: "Cloaking",

    # MAP VARIANT SCENERY STARTS
    62: "Fusion Coil",
    63: "Crate",
    64: "Container, Double",
    65: "Container Double, Open",
    66: "Container",
    67: "Container, Open",
    68: "Steel Ramp",
    69: "Bridge",
    70: "Wall, Corner, Short",
    71: "Steel Wall",
    72: "Steel Barrier",
    73: "Steel Wall, Corner",
    74: "Watchtower Base",
    75: "Energy Blocker, Small",
    76: "Energy Blocker, Large",
    77: "Weapon Holder",
    78: "Power Core",
    79: "Grav Lift",
    80: "Shield Door, Large",
    81: "Shield Door",
    82: "Cannon, Man",
    83: "Soccer Ball",
    84: "FX, Nova",
    85: "FX, Pen And Ink",
    86: "FX, Olde Timey",
    87: "FX, Colorblind",
    88: "FX, Gloomy",
    89: "FX, Juicy",
    90: "Double Box",
    91: "Double Box, Open",
    92: "Single Box",
    93: "Single Box, Open",
    94: "Fence Box",
    95: "Fence Wall",
    96: "Stairs",
    97: "Sign A",
    98: "Sign B",
    99: "Wall",
    100: "Wall, Double",
    101: "Wall, Corner",
    102: "Scaffolding",
    103: "Wood Bridge, Large",
    104: "Wood Bridge, Thin",
    105: "Door, Small",
    106: "Door, Medium",
    107: "Door, Large",
    108: "Forerunner Crate, Blue",
    109: "Forerunner Crate, Red",
    110: "Tube Shield",
    111: "Blue Light",
    112: "Red Light",
    113: "Kill Ball",
    114: "Tin Cup",
    115: "Golf Ball",
    116: "7-Wood",
    117: "Ramp Covenant",
    118: "Roadblock",
    119: "Street Cone",
    120: "Barricade",
    121: "Plasma Battery",
    # MAP VARIANT SCENERY ENDS

    # MAP VARIANT TELEPORTERS START
    122: "Sender Node",
    123: "Receiver Node",
    124: "Two-Way Node",
    # MAP VARIANT TELEPORTERS END

    # MAP VARIANT SPAWNERS START
    125: "CTF Flag Spawn Point",
    126: "CTF Flag Return Area",
    127: "Assault Bomb Spawn Point",
    128: "Assualt Bomb Goal Area",
    129: "Juggernaut Destination Static",
    130: "Hill Static",
    131: "Oddball Spawn Point",
    132: "Territory Static",
    133: "VIP Destination Static",


    134: "Respawn Point",
    135: "Assault Initial Spawn Point",
    136: "CTF Initial Spawn Point",
    137: "Hill Initial Spawn Point",
    138: "Oddball Initial Spawn Point",
    139: "Slayer Initial Spawn Point",
    140: "Territories Initial Spawn Point",
    141: "VIP Initial Spawn Point",
    142: "Assault Respawn Zone",
    143: "CTF Respawn Zone",
    144: "CTF Flag At Home Respawn Zone",
    145: "CTF Flag Away Respawn Zone",
    146: "Hill Respawn Zone",
    147: "Oddball Respawn Zone",
    148: "Slayer Respawn Zone",
    149: "Territories Respawn Zone",
    150: "VIP Respawn Zone",
    151: "Infection Initial Spawn Point",
    152: "Infection Respawn Zone",
}