# Waterfall Item List

waterfallItems = {
    # MV Vehicle Pallette
    0: "Ghost",
    1: "Mongoose",
    2: "Warthog, Wrecked",
    3: "Warthog",
    4: "Warthog, Gauss",
   
    # MV Weapon Pallette
    5: "Assault Rifle",
    6: "Battle Rifle",
    7: "Shotgun",
    8: "Sniper Rifle",
    9: "SMG",
    10: "Silenced SMG",
    11: "Spiker",
    12: "Magnum",
    13: "Automag",
    14: "Plasma Pistol",
    15: "Plasma Rifle",
    16: "Brute Plasma Rifle",
    17: "Needler",
    18: "Brute Shot",
    19: "Rocket Launcher",
    20: "Spartan Laser",
    21: "Energy Sword",
    22: "Gravity Hammer",
    23: "7-Wood",
    24: "Carbine",
    25: "Mauler",
    26: "Fuel Rod Cannon",
    27: "Sentinel Beam",
    28: "Machine Gun Turret",
    29: "Plasma Cannon",
    30: "Flamethrower",
    31: "Missile Pod",
    32: "Beam Rifle",

    # MV Equipment Pallette
    33: "Frag Grenade",
    34: "Plasma Grenade",
    35: "Spike Grenade",
    36: "Firebomb Grenade",
    37: "Bubble Shield",
    38: "Power Drain",
    39: "Trip Mine",
    40: "Grav Lift",
    41: "Regenerator",
    42: "Radar Jammer",
    43: "Flare",
    44: "Deployable Cover",
    48: "Auto-Turret",
    45: "Overshields",
    46: "Active Camo",
    47: "Custom Powerup",
    48: "SPNKR Ammo",
    49: "Invincibility",
    50: "Cloaking",

    # MV Scenery Pallette
    51: "Supply Case",
    52: "Crate",
    53: "Generator",
    54: "Server",
    55: "Double Box",
    56: "Double Box, Open",
    57: "Single Box",
    58: "Single Box, Open",
    59: "Fence Wall",
    60: "Fence Box",
    61: "Stairs",
    62: "Wall",
    63: "Wall, Double",
    64: "Wall, Corner",
    65: "Bridge",
    66: "Sign A",
    67: "Sign B",
    68: "Door, Small",
    69: "Door, Medium",
    70: "Door, Large",
    71: "Roadblock",
    72: "Soccer Ball",
    73: "Street Cone",
    74: "Forklift",
    75: "Cart, Electric",
    76: "Dinghy",
    77: "Fusion Coil",
    78: "Pallet",
    79: "Grav Lift",
    80: "Cannon, Man",
    81: "Shield Door, Large",
    82: "Shield Door",
    83: "Weapon Holder",
    84: "Blue Light",
    85: "Red Light",
    86: "FX, Nova",
    87: "FX, Pen And Ink",
    88: "FX, Olde Timey",
    89: "FX, Colorblind",
    90: "FX, Gloomy",
    91: "FX, Juicy",

    # MV Teleporter Pallette
    92: "Sender Node",
    93: "Receiver Node",
    94: "Two-Way Node",

    # MV Goals Pallette
    95: "CTF Spoawn Point",
    96: "CTF Return Area",
    97: "Assault Spawn Point",
    98: "Assault Goal Area",
    99: "Juggernaut Destination Static",
    100: "Hill Static",
    101: "Oddball Spawn Point",
    102: "Territory Static",
    103: "VIP Destination Static",

    # MV Spawners Pallette
    104: "Respawn Point",
    105: "Assault Initial Spawn Point",
    106: "CTF Initial Spawn Point",
    107: "Hill Initial Spawn Point",
    108: "Oddball Initial Spawn Point",
    109: "Slayer Initial Spawn Point",
    110: "Territories Initial Spawn Point",
    111: "VIP Initial Spawn Point",
    112: "Assault Respawn Zone",
    113: "CTF Respawn Zone",
    114: "CTF Flag At Home Respawn Zone",
    115: "CTF Flag Away Respawn Zone",
    116: "Hill Respawn Zone",
    117: "Oddball Respawn Zone",
    118: "Slayer Respawn Zone",
    119: "Slayer Respawn Zone",
    120: "Territories Respawn Zone",
    121: "VIP Respawn Zone",
    122: "Infection Initial Spawn Point",
    123: "Infection Respawn Zone"

}
