# Isolation Item List

isolationItems = {
    # MV Vehicle Pallette
    0: "Warthog",
    1: "Mongoose",
    2: "Ghost",
    3: "Chopper",
    4: "Banshee",

    # MV Weapon Pallette
    5: "Assault Rifle",
    6: "Battle Rifle",
    7: "Shotgun",
    8: "Sniper Rifle",
    9: "SMG",
    10: "Spiker",
    11: "Magnum",
    12: "Plasma Pistol",
    13: "Plasma Rifle",
    14: "Needler",
    15: "Beam Rifle",
    16: "Brute Shot",
    17: "Rocket Launcher",
    18: "Spartan Laser",
    19: "Energy Sword",
    20: "Machine Gun Turret",
    21: "Gravity Hammer",
    22: "Missile Pod",
    23: "Carbine",
    24: "Mauler",
    25: "Sentinel Beam",
    26: "Fuel Rod Gun",
    27: "Silenced SMG",
    28: "Automag",
    29: "Brute Plasma Rifle",
    30: "Plasma Cannon",
    31: "Flamethrower",
    32: "7-Wood",

    # MV Equipment Pallette
    33: "Frag Grenade",
    34: "Plasma Grenade",
    35: "Spike Grenade",
    36: "Firebomb Grenade",
    37: "Bubble Shield",
    38: "Power Drain",
    39: "Trip Mine",
    40: "Grav Lift",
    41: "Regenerator",
    42: "Radar Jammer",
    43: "Flare",
    44: "Deployable Cover",
    45: "Overshields",
    46: "Active Camo",
    47: "Custom Powerup",
    48: "Auto-Turret",
    49: "Invincibility",
    50: "Cloaking",

    # MV Scenery Pallette
    51: "Power Core",
    52: "Fusion Coil",
    53: "Crate, Single",
    54: "Crate",
    55: "Turret Case",
    56: "Radio Antennae",
    57: "Camping Stool",
    58: "Drum, 55 Gal",
    59: "Equipment Case",
    60: "Radio Set, Small",
    61: "Drop Pod, Closed",
    62: "Drop Pod, Panel",
    63: "Barricade",
    64: "Medical Crate",
    65: "Computer, Small",
    66: "Blitz Can",
    67: "Supply Case",
    68: "Plasma Battery",
    69: "Grav Lift",
    70: "Weapon Holder",

    # MV Teleporter Pallette
    71: "Sender Node",
    72: "Receiver Node",
    73: "Two-Way Node",

    # MV Goals Pallette
    74: "CTF Spoawn Point",
    75: "CTF Return Area",
    76: "Assault Spawn Point",
    77: "Assault Goal Area",
    78: "Juggernaut Destination Static",
    79: "Hill Static",
    80: "Oddball Spawn Point",
    81: "Territory Static",
    82: "VIP Destination Static",

    # MV Spawners Pallette
    83: "Respawn Point",
    84: "Assault Initial Spawn Point",
    85: "CTF Initial Spawn Point",
    86: "Hill Initial Spawn Point",
    87: "Oddball Initial Spawn Point",
    88: "Slayer Initial Spawn Point",
    89: "Territories Initial Spawn Point",
    90: "VIP Initial Spawn Point",
    91: "Assault Respawn Zone",
    92: "CTF Respawn Zone",
    93: "CTF Flag At Home Respawn Zone",
    94: "CTF Flag Away Respawn Zone",
    95: "Hill Respawn Zone",
    96: "Oddball Respawn Zone",
    97: "Slayer Respawn Zone",
    98: "Territories Respawn Zone",
    99: "VIP Respawn Zone",
    100: "Infection Initial Spawn Point",
    101: "Infection Respawn Zone"

}
