# Construct Item List

constructItems = {
    # MV Vehicle Pallette
    0: "Mongoose",
    1: "Banshee",
    2: "Hornet",

    # MV Weapon Pallette
    3: "Assault Rifle",
    4: "Battle Rifle",
    5: "Shotgun",
    6: "Sniper Rifle",
    7: "SMG",
    8: "Spiker",
    9: "Magnum",
    10: "Plasma Pistol",
    11: "Plasma Rifle",
    12: "Needler",
    13: "Beam Rifle",
    14: "Brute Shot",
    15: "Rocket Launcher",
    16: "Spartan Laser",
    17: "Energy Sword",
    18: "Machine Gun Turret",
    19: "Gravity Hammer",
    20: "Missile Pod",
    21: "Carbine",
    22: "Mauler",
    23: "Sentinel Beam",
    24: "Flamethrower",
    25: "Fuel Rod Gun",
    26: "Silenced SMG",
    27: "Automag",
    28: "Brute PLasma Rifle",
    29: "Plasma Cannon",
    30: "7-Wood",

    # MV Equipment Pallette
    31: "Frag Grenade",
    32: "Plasma Grenade",
    33: "Spike Grenade",
    34: "Firebomb Grenade",
    35: "Bubble Shield",
    36: "Power Drain",
    37: "Trip Mine",
    38: "Grav Lift",
    39: "Regenerator",
    40: "Radar Jammer",
    41: "Flare",
    42: "Deployable Cover",
    43: "Overshields",
    44: "Active Camo",
    45: "Custom Powerup",
    46: "Auto-Turret",
    47: "Invincibility",
    48: "Cloaking",

    # MV Scenery Pallette
    49: "Fusion Coil",
    50: "Crate, Single",
    51: "Crate",
    52: "Turret Case",
    53: "Radio Antennae",
    54: "Camping Stool",
    55: "Drum, 55 Gal",
    56: "Equipment Case",
    57: "Radio Set, Small",
    58: "Drop Pod, Closed",
    59: "Drop Pod, Pane;",
    60: "Barricade",
    61: "Medical Crate",
    62: "Computer, Small",
    63: "Rucksack",
    64: "Blitz Can",
    65: "Supply Case",
    66: "Plasma Battery",
    67: "Grav Lift",
    68: "Power Core",
    69: "Weapomn Holder",

    # MV Teleporter Pallette
    70: "Sender Node",
    71: "Receiver Node",
    72: "Two-Way Node",

    # MV Goals Pallette
    73: "CTF Flag Spawn Point",
    74: "CTF Flag Return Area",
    75: "Assault Bomb Spawn Point",
    76: "Assault Bomb Goal Area",
    77: "Juggernaut Destination Static",
    78: "Hill Static",
    79: "Oddball Spawn Point",
    80: "Territory Static",
    81: "VIP Destination Static",

    # MV Spawners Pallette
    82: "Respawn Point",
    83: "Assault Initial Spawn Point",
    84: "CTF Initial Spawn Point",
    85: "Hill Initial Spawn Point",
    86: "Oddball Initial Spawn Point",
    87: "Slayer Initial Spawn Point",
    88: "Territories Initial Spawn Point",
    89: "VIP Initial Spawn Point",
    90: "Assault Respawn Zone",
    91: "CTF Respawn Zone",
    92: "CTF Flag At Home Respawn Zone",
    93: "CTF Flag Away Respawn Zone",
    94: "Hill Respawn Zone",
    95: "Oddball Respawn Zone",
    96: "Slayer Respawn Zone",
    97: "Territories Respawn Zone",
    98: "VIP Respawn Zone",
    99: "Infection Initial Spawn Point",
    100: "Infection Respawn Zone"
}
