#Assembly Item List

assemblyItems = {
    # MV Vehicle Pallette
    0: "Ghost",
    1: "Mongoose",

    # MV Weapon Pallette
    2: "Assault Rifle",
    3: "Battle Rifle",
    4: "Beam Rifle",
    5: "Brute Shot",
    6: "Carbine",
    7: "Energy Sword",
    8: "Flamethrower",
    9: "Fuel Rod Gun",
    10: "Gravity Hammer",
    11: "Machine Gun Turret",
    12: "Magnum",
    13: "Mauler",
    14: "Needler",
    15: "Plasma Cannon",
    16: "Plasma Pistol",
    17: "Plasma Rifle",
    18: "Rocket Launcher",
    19: "Shotgun",
    20: "SMG",
    21: "Sniper Rifle",
    22: "Spartan Laser",
    23: "Spiker",
    24: "Sentinel Beam",
    25: "Silenced SMG",
    26: "Automag",
    27: "Brute Plasma Rifle",
    28: "Missile Pod",
    29: "7-Wood",
   
   # MV Equipment Pallette
    30: "Frag Grenade",
    31: "Plasma Grenade",
    32: "Spike Grenade",
    33: "Firebomb Grenade",
    34: "Bubble Shield",
    35: "Power Drain",
    36: "Trip Mine",
    37: "Grav Lift",
    38: "Regenerator",
    39: "Radar Jammer",
    40: "Flare",
    41: "Deployable Cover",
    42: "Overshields",
    43: "Active Camo",
    44: "Custom Powerup",
    45: "Auto-Turret",
    46: "Invincibility",
    47: "Cloaking",

    # MV Scenery Pallette
    48: "Barrier",
    49: "Camping Stool",
    50: "Comm Node",
    51: "Plasma Battery",
    52: "Power Core",
    53: "Tube Shield",
    54: "Supply Case, Open",
    55: "Supply Case",
    56: "Lift Blocker",
    57: "Weapon Holder",
    58: "Grav Lift",
    59: "Shield Door, Large",
    60: "Shield Door",
    61: "Cannon, Man",
    62: "Soccer Ball",
    63: "FX, Nova",
    64: "FX, Pen And Ink",
    65: "FX, Olde Timey",
    66: "FX, Colorblind",
    67: "FX, Gloomy",
    68: "FX, Juicy",
    

    # MV Teleporters Pallette
    69: "Sender Node",
    70: "Receiver Node",
    71: "Two-Way Node",

    # MV Goals Pallette
    72: "Respawn Point",
    73: "Assault Bomb Goal Area",
    74: "Assault Bomb Spawn Point",
    75: "CTF Return Area",
    76: "CTF Spawn Point",
    77: "Juggernaut Destination Static",
    78: "Hill Static",
    79: "Oddball Spawn Point",
    80: "Territory Static",
    81: "VIP Destination Static",


    # MV Spawners Pallette
    82: "Assault Initial Spawn Point",
    83: "CTF Initial Spawn Point",
    84: "Hill Initial Spawn Point",
    85: "Oddball Initial Spawn Point",
    86: "Slayer Initial Spawn Point",
    87: "Territories Initial Spawn Point",
    88: "VIP Initial Spawn Point",
    89: "Assault Respawn Zone",
    90: "CTF Respawn Zone",
    91: "CTF Flag At Home Respawn Zone",
    92: "CTF Flag Away Respawn Zone",
    93: "Hill Respawn Zone",
    94: "Oddball Respawn Zone",
    95: "Slayer Respawn Zone",
    96: "Territories Respawn Zone",
    97: "VIP Respawn Zone",
    98: "Infection Initial Spawn Point",
    99: "Infection Respawn Zone",

    102: "box_l",
    103: "box_m",
    104: "box_xl",
    105: "box_xxl",
    106: "box_xxxl",
    107: "wall_l",
    108: "wall_m",
    109: "wall_xl",
    110: "wall_xxl",
    111: "wall_xxxl",
}
