# Ratsnest Item List

ratsnestItems = {
    0: "Warthog",
    1: "Mongoose",
    2: "Ghost",
    3: "Warthog, Gauss",
    4: "Chopper",
    5: "Scorpion",

    6: "Assault Rifle",
    7: "Battle Rifle",
    8: "Shotgun",
    9: "Sniper Rifle",
    10: "SMG",
    11: "Spiker",
    12: "Magnum",
    13: "Plasma Pistol",
    14: "Plasma Rifle",
    15: "Needler",
    16: "Beam Rifle",
    17: "Brute Shot",
    18: "Rocket Launcher",
    19: "Spartan Laser",
    20: "Energy Sword",
    21: "Machine Gun Turret",
    22: "Gravity Hammer",
    23: "Missile Pod",
    24: "Mauler",
    25: "Flamethrower",
    26: "Fuel Rod Gun",
    27: "Sentinel Beam",
    28: "Carbine",
    29: "Silenced SMG",
    30: "Automag",
    31: "Brute Plasma Rifle",
    32: "Plasma Cannon",
    33: "7-Wood",

    34: "Frag Grenade",
    35: "Plasma Grenade",
    36: "Spike Grenade",
    37: "Firebomb Grenade",
    38: "Bubble Shield",
    39: "Power Drain",
    40: "Trip Mine",
    41: "Grav Lift",
    42: "Regenerator",
    43: "Radar Jammer",
    44: "Flare",
    45: "Deployable Cover",
    46: "Overshields",
    47: "Active Camo",
    48: "Custom Powerup",
    49: "Auto-Turret",
    50: "Invincibility",
    51: "Cloaking",


    52: "Fusion Coil",
    53: "Crate, Single",
    54: "Crate",
    55: "Camping Stool",
    56: "Drum, 55 Gal",
    57: "Equipment Case",
    58: "Radio Set, Small",
    59: "Container",
    60: "Container, Open",
    61: "Street Cone",
    62: "Forklift",
    63: "Barrier",
    64: "Roadblock",
    65: "Pallet",
    66: "Garbage Can",
    67: "Propane Tank",
    68: "Barrel",
    69: "Barrel, Small",
    70: "Missile, Body",
    71: "Wire Spool",
    72: "Double Box, Open",
    73: "Bridge",
    74: "Weapon Holder",
    75: "Grav Lift",
    76: "Shield Door, Large",
    77: "Shield Door",
    78: "Cannon, Man",
    79: "Soccer Ball",
    
    
    80: "Sender Node",
    81: "Receiver Node",
    82: "Two-Way Node",


    83: "Respawn Point",
    84: "CTF Flag Spawn Point",
    85: "CTF Flag Return Area",
    86: "Assault Bomb Spawn Point",
    87: "Assualt Bomb Goal Area",
    88: "Juggernaut Destination Static",
    89: "Hill Static",
    90: "Oddball Spawn Point",
    91: "Territory Static",


    92: "Assault Initial Spawn Point",
    93: "CTF Initial Spawn Point",
    94: "Hill Initial Spawn Point",
    95: "Oddball Initial Spawn Point",
    96: "Slayer Initial Spawn Point",
    97: "STerritories Initial Spawn Point",
    98: "VIP Initial Spawn Point",
    99: "Assault Initial Spawn Point",
    100: "CTF Respawn Zone",
    101: "CTF Flag At Home Respawn Zone",
    102: "CTF Flag Away Respawn Zone",
    103: "Hill Respawn Zone",
    104: "Oddball Respawn Zone",
    105: "Slayer Respawn Zone",
    106: "Territories Respawn Zone",
    107: "VIP Respawn Zone",
    108: "Infection Initial Spawn Point",
    109: "Infection Respawn Zone",

    111: "Respawn Point Invisible",
    112: "box_l",
    113: "box_m",
    114: "box_xl",
    115: "box_xxl",
    116: "box_xxxl",
    117: "wall_l",
    118: "wall_m",
    119: "wall_xl",
    120: "wall_xxl",
    121: "wall_xxxl",


}
