# Edge Item List

edgeItems = {
    # MV Vehicle Pallette
    0: "Ghost",
    1: "Mongoose",
    2: "Warthog, Wrecked",
    3: "Warthog",
    4: "Warthog, Gauss",
   

    # MV Weapon Pallette
    5: "Assault Rifle",
    6: "Battle Rifle",
    7: "Shotgun",
    8: "Sniper Rifle",
    9: "SMG",
    10: "Spiker",
    11: "Magnum",
    12: "Plasma Pistol",
    13: "Plasma Rifle",
    14: "Needler",
    15: "Brute Shot",
    16: "Rocket Launcher",
    17: "Spartan Laser",
    18: "Energy Sword",
    19: "Plasma Cannon",
    20: "Gravity Hammer",
    21: "Mauler",
    22: "Carbine",
    23: "Machine Gun Turret",
    24: "Flamethrower",
    25: "Fuel Rod Gun",
    26: "Beam Rifle",
    27: "Sentinel Beam",
    28: "Silenced SMG",
    29: "Automag",
    30: "Brute Plasma Rifle",
    31: "7-Wood",
    32: "Missile Pod",

    # MV Equipment Pallette
    33: "Frag Grenade",
    34: "Plasma Grenade",
    35: "Spike Grenade",
    36: "Firebomb Grenade",
    37: "Bubble Shield",
    38: "Power Drain",
    39: "Trip Mine",
    40: "Grav Lift",
    41: "Regenerator",
    42: "Radar Jammer",
    43: "Flare",
    44: "Deployable Cover",
    45: "Overshield",
    46: "Active Camo",
    47: "Custom Powerup",
    48: "Auto-Turret",
    49: "Invincibility",
    50: "Cloaking",

    # MV Scenery Pallette
    51: "Radio Set",
    52: "Rucksack",
    53: "Drum, 55 Gal",
    54: "Camping Stool",
    55: "Crate, Single",
    56: "Crate",
    57: "Barrel",
    58: "Barrel, Small",
    59: "Pallet",
    60: "Roadblock",
    61: "Street Cone",
    62: "Plasma Battery",
    63: "Power Core",
    64: "Turret Case",
    65: "Generator, Small",
    66: "Weapon Holder",
    67: "Grav Lift",
    68: "Blue Light",
    69: "Red Light",
    70: "Wall, Corner, Short",
    71: "Steel Wall",
    72: "Steel Barrier",
    73: "Steel Wall, Corner",
    74: "Steel Ramp",
    75: "Energy Blocker, Small",
    76: "Energy Blocker, Large",
    77: "Forerunner Crate, Blue",
    78: "Forerunner Crate, Red",
    79: "Tube Shield",
    80: "Kill Ball",
    81: "Tin Cup",
    82: "Golf Ball",
    83: "7-Wood",
    84: "Soccer Ball",
    85: "Energy Blocker, Smaller",
    86: "Energy Blocker, Tiny",
    87: "FX, Olde Timey",
    88: "FX, Colorblind",
    89: "FX, Gloomy",
    90: "FX, Juicy",
    91: "FX, Pen And Ink",
    92: "FX, Nova",


    # MV Teleporter Pallette
    93: "Sender Node",
    94: "Receiver Node",
    95: "Two-Way Node",

    # MV Goals Pallette
    96: "CTF Spoawn Point",
    97: "Respawn Point",
    98: "CTF Return Area",
    99: "Assault Spawn Point",
    100: "Assault Goal Area",
    101: "Juggernaut Destination Static",
    102: "Hill Static",
    103: "Oddball Spawn Point",
    104: "Territory Static",
    105: "VIP Destination Static",

    # MV Spawners Pallette
    106: "Assault Initial Spawn Point",
    107: "CTF Initial Spawn Point",
    108: "Hill Initial Spawn Point",
    109: "Oddball Initial Spawn Point",
    110: "Slayer Initial Spawn Point",
    111: "Territories Initial Spawn Point",
    112: "VIP Initial Spawn Point",
    113: "Assault Respawn Zone",
    114: "CTF Respawn Zone",
    115: "CTF Flag At Home Respawn Zone",
    116: "CTF Flag Away Respawn Zone",
    117: "Hill Respawn Zone",
    118: "Oddball Respawn Zone",
    119: "Slayer Respawn Zone",
    120: "Territories Respawn Zone",
    121: "VIP Respawn Zone",
    122: "Infection Initial Spawn Point",
    123: "Infection Respawn Zone",

    125: "Respawn Point Invisible",
    126: "box_l",
    127: "box_xxl",
    128: "box_m",
    129: "wall_l",
    # 130: "box_xxxl",
    # 131: "wall_l",
    # 132: "wall_m",
    # 133: "wall_xl",
    # 134: "wall_xxl",
    # 135: "wall_xxxl",

}
