# Ratsnest Item List

ratsnestItems = {
    0: "Warthog",
    1: "Mongoose",
    2: "Ghost",
    3: "Warthog, Gauss",
    4: "Chopper",
    5: "Scorpion",

    6: "Assault Rifle",
    7: "Battle Rifle",
    8: "Shotgun",
    9: "Sniper Rifle",
    10: "SMG",
    11: "Spiker",
    12: "Magnum",
    13: "Plasma Pistol",
    14: "Plasma Rifle",
    15: "Needler",
    16: "Beam Rifle",
    17: "Brute Shot",
    18: "Rocket Launcher",
    19: "Spartan Laser",
    20: "Energy Sword",
    21: "Machine Gun Turret",
    22: "Gravity Hammer",
    23: "Missile Pod",
    24: "Mauler",
    25: "Flamethrower",
    26: "Fuel Rod Gun",
    27: "Sentinel Beam",
    28: "Carbine",
    29: "Silenced SMG",
    30: "Automag",
    31: "Brute Plasma Rifle",
    32: "Plasma Cannon",
    33: "7-Wood",

    34: "Frag Grenade",
    35: "Plasma Grenade",
    36: "Spike Grenade",
    37: "Firebomb Grenade",
    38: "Bubble Shield",
    39: "Power Drain",
    40: "Trip Mine",
    41: "Grav Lift",
    42: "Regenerator",
    43: "Radar Jammer",
    44: "Flare",
    45: "Deployable Cover",
    46: "Overshields",
    47: "Active Camo",
    48: "Custom Powerup",
    49: "Auto-Turret",
    50: "Invincibility",
    51: "Cloaking",


    52: "Fusion Coil",
    53: "Crate, Single",
    54: "Crate",
    55: "Camping Stool",
    56: "Drum, 55 Gal",
    57: "Equipment Case",
    58: "Radio Set, Small",
    59: "Container",
    60: "Container, Open",
    61: "Street Cone",
    62: "Forklift",
    63: "Barrier",
    64: "Roadblock",
    65: "Pallet",
    66: "Garbage Can",
    67: "Propane Tank",
    68: "Barrel",
    69: "Barrel, Small",
    70: "Missile, Body",
    71: "Wire Spool",
    72: "Double Box, Open",
    73: "Bridge",
    74: "Weapon Holder",
    75: "Grav Lift",
    76: "Shield Door, Large",
    77: "Shield Door",
    78: "Cannon, Man",
    79: "Soccer Ball",
    80: "Propane Tank",
    81: "Weapon Holder",
    82: "Grav Lift",
    83: "Cannon, Man",
    84: "Shield Door, Large",
    85: "Shield Door",
    86: "Soccer Ball",
    

    87: "Sender Node",
    88: "Receiver Node",
    89: "Two-Way Node",


    90: "CTF Flag Spawn Point",
    91: "CTF Flag Return Area",
    92: "Assault Bomb Spawn Point",
    93: "Assualt Bomb Goal Area",
    94: "Juggernaut Destination Static",
    95: "Hill Static",
    96: "Oddball Spawn Point",
    97: "Territory Static",


    98: "Respawn Point",
    99: "Assault Initial Spawn Point",
    100: "CTF Initial Spawn Point",
    101: "Hill Initial Spawn Point",
    102: "Oddball Initial Spawn Point",
    103: "Slayer Initial Spawn Point",
    104: "STerritories Initial Spawn Point",
    105: "VIP Initial Spawn Point",
    106: "Assault Initial Spawn Point",
    107: "CTF Respawn Zone",
    108: "CTF Flag At Home Respawn Zone",
    109: "CTF Flag Away Respawn Zone",
    110: "Hill Respawn Zone",
    111: "Oddball Respawn Zone",
    112: "Slayer Respawn Zone",
    113: "CTerritories Respawn Zone",
    114: "VIP Respawn Zone",
    115: "CInfection Initial Spawn Point",
    116: "Infection Respawn Zone",

}
