#Valhalla Item List

valhallaItems = {
    # MV Vehicle Pallette
    0: "Warthog",
    1: "Mongoose",
    2: "Ghost",
    3: "Chopper",
    4: "Wraith",
    5: "Banshee",
    6: "Hornet",
    7: "Scorpion",

    # MV Weapon Pallette
    8: "Assault Rifle",
    9: "Battle Rifle",
    10: "Shotgun",
    11: "Sniper Rifle",
    12: "SMG",
    13: "Spiker",
    14: "Magnum",
    15: "Plasma Pistol",
    16: "Needler",
    17: "Beam Rifle",
    18: "Brute Shot",
    19: "Rocket Launcher",
    20: "Spartan Laser",
    21: "Energy Sword",
    22: "Machine Gun Turret",
    23: "Gravity Hammer",
    24: "Missile Pod",
    25: "Sentinel Beam",
    26: "Carbine",
    27: "Plasma Rifle",
    28: "Mauler",
    29: "Fuel Rod Gun",
    30: "Silenced SMG",
    31: "Automag",
    32: "Brute Plasma Rifle",
    33: "Plasma Cannon",
    34: "Flamethrower",
    35: "7-Wood",

    # MV Equipment Pallette
    36: "Frag Grenade",
    37: "Plasma Grenade",
    38: "Spike Grenade",
    39: "Firebomb Grenade",
    40: "Bubble Shield",
    41: "Power Drain",
    42: "Trip Mine",
    43: "Grav Lift",
    44: "Regenerator",
    45: "Radar Jammer",
    46: "Flare",
    47: "Deployable Cover",
    48: "Overshields",
    49: "Active Camo",
    50: "Custom Powerup",
    51: "Auto-Turret",
    52: "Invincibility",
    53: "Cloaking",

    # MV Scenery Pallette
    54: "Fusion Coil",
    55: "Crate, Single",
    56: "Crate",
    57: "Turret Case",
    58: "Radio Antennae",
    59: "Camping Stool",
    60: "Drum, 55 Gal",
    61: "Equipment Case",
    62: "Radio Set, Small",
    63: "Drop Pod, Closed",
    64: "Drop Pod, Panel",
    65: "Barricade",
    66: "Medical Crate",
    67: "Grav Lift",
    68: "Weapon Holder",

    # MV Teleporter Pallette
    69: "Sender Node",
    70: "Receiver Node",
    71: "Two-Way Node",

    # MV Goals Pallette
    72: "Respawn Point",
    73: "CTF Spoawn Point",
    74: "CTF Return Area",
    75: "Assault Spawn Point",
    76: "Assault Goal Area",
    77: "Juggernaut Destination Static",
    78: "Hill Static",
    79: "Oddball Spawn Point",
    80: "Territory Static",
    81: "VIP Destination Static",

    # MV Spawners Pallette
    82: "Assault Initial Spawn Point",
    83: "CTF Initial Spawn Point",
    84: "Hill Initial Spawn Point",
    85: "Oddball Initial Spawn Point",
    86: "Slayer Initial Spawn Point",
    87: "Territories Initial Spawn Point",
    88: "VIP Initial Spawn Point",
    89: "Assault Respawn Zone",
    90: "CTF Respawn Zone",
    91: "CTF Flag At Home Respawn Zone",
    92: "CTF Flag Away Respawn Zone",
    93: "Hill Respawn Zone",
    94: "Oddball Respawn Zone",
    95: "Slayer Respawn Zone",
    96: "Territories Respawn Zone",
    97: "VIP Respawn Zone",
    98: "Infection Initial Spawn Point",
    99: "Infection Respawn Zone",

    100: "Respawn Point Invisible",
    105: "box_l",
    106: "box_m",
    107: "box_xl",
    108: "box_xxl",
    109: "box_xxxl",
    110: "wall_l",
    111: "wall_m",
    112: "wall_xl",
    113: "wall_xxl",
    114: "wall_xxxl",
}
