# Icebox Item List

iceboxItems = {
    # MV Vehicle Pallette
    0: "Warthog",
    1: "Warthog, Gauss",
    2: "Mongoose",
    3: "Ghost",
    4: "Warthog, Wrecked",
   
    # MV Weapon Pallette
    5: "Assault Rifle",
    6: "Battle Rifle",
    7: "Shotgun",
    8: "Sniper Rifle",
    9: "SMG",
    10: "Silenced SMG",
    11: "Spiker",
    12: "Magnum",
    13: "Automag",
    14: "Plasma Pistol",
    15: "Plasma Rifle",
    16: "Brute Plasma Rifle",
    17: "Needler",
    18: "Brute Shot",
    19: "Rocket Launcher",
    20: "Spartan Laser",
    21: "Energy Sword",
    22: "Plasma Cannon",
    23: "Gravity Hammer",
    24: "Mauler",
    25: "Carbine",
    26: "Machine Gun Turret",
    27: "Flamethrower",
    28: "Fuel Rod Gun",
    29: "Beam Rifle",
    30: "Sentinel Beam",
    31: "7-Wood",
    32: "Missile Pod",

    # MV Equipment Pallette
    33: "Frag Grenade",
    34: "Plasma Grenade",
    35: "Spike Grenade",
    36: "Firebomb Grenade",
    37: "Bubble Shield",
    38: "Power Drain",
    39: "Trip Mine",
    40: "Grav Lift",
    41: "Regenerator",
    42: "Radar Jammer",
    43: "Flare",
    44: "Deployable Cover",
    45: "Overshields",
    46: "Active Camo",
    47: "Custom Powerup",
    48: "Auto-Turret",
    49: "Invincibility",
    50: "Cloaking",

    # MV Scenery Pallette
    51: "Fusion Coil",
    52: "Crate",
    53: "Container, Double",
    54: "Container, Double, Open",
    55: "Container",
    56: "Container, Open",
    57: "Double Box",
    58: "Double Box, Open",
    59: "Single Box",
    60: "Single Box, Open",
    61: "Container",
    62: "Supply Case",
    63: "Crate, Single",
    64: "Forerunner Crate, Blue",
    65: "Forerunner Crate, Red",
    66: "Energy Blocker, Small",
    67: "Energy Blocker, Large",
    68: "Fence Box",
    69: "Fence Wall",
    70: "Stairs",
    71: "Ramp, Covenant",
    72: "Bridge",
    73: "Sign A",
    74: "Sign B",
    75: "Wall",
    76: "Wall, Double",
    77: "Wall, Corner",
    78: "Scaffolding",
    79: "Wood Bridge, Large",
    80: "Wood Bridge, Thin",
    81: "Roadblock",
    82: "Street Cone",
    83: "Barricade",
    84: "Forklift",
    85: "Pallet",
    86: "Barricade",
    87: "Garbage Can",
    88: "Dumpster",
    89: "Medical Cabinet",
    90: "Barrier",
    91: "Door, Small",
    92: "Door, Medium",
    93: "Door, Large",
    94: "Plasma Battery",
    95: "Weapon Holder",
    96: "Grav Lift",
    97: "Cannon, Man",
    98: "Watchtower Base",
    99: "Power Core",
    100: "Shield Door, Large",
    101: "Shield Door",
    102: "Steel Ramp",
    103: "Wall, Corner, Short",
    104: "Steel Wall",
    105: "Steel Barrier",
    106: "Steel Wall, Corner",
    107: "Tube Shield",
    108: "Soccer Ball",
    109: "Blue Light",
    110: "Red Light",
    111: "Kill Ball",
    112: "Tin Cup",
    113: "Golf Ball",
    114: "7-Wood",
    115: "FX, Nova",
    116: "FX, Pen And Ink",
    117: "FX, Olde Timer",
    118: "FX, Colorblind",
    119: "FX, Gloomy",
    120: "FX, Juicy",

    # MV Teleporter Pallette
    121: "Sender Node",
    122: "Receiver Node",
    123: "Two-Way Node",

    # MV Goals Pallette
    124: "CTF Spoawn Point",
    125: "CTF Return Area",
    126: "Assault Spawn Point",
    127: "Assault Goal Area",
    128: "Juggernaut Destination Static",
    129: "Hill Static",
    130: "Oddball Spawn Point",
    131: "Territory Static",
    132: "VIP Destination Static",

    # MV Spawners Pallette
    133: "Respawn Point",
    134: "Assault Initial Spawn Point",
    135: "CTF Initial Spawn Point",
    136: "Hill Initial Spawn Point",
    137: "Oddball Initial Spawn Point",
    138: "Slayer Initial Spawn Point",
    139: "Territories Initial Spawn Point",
    140: "VIP Initial Spawn Point",
    141: "Assault Respawn Zone",
    142: "CTF Respawn Zone",
    143: "CTF Flag At Home Respawn Zone",
    144: "CTF Flag Away Respawn Zone",
    145: "Hill Respawn Zone",
    146: "Oddball Respawn Zone",
    147: "Slayer Respawn Zone",
    148: "Territories Respawn Zone",
    149: "VIP Respawn Zone",
    150: "Infection Initial Spawn Point",
    151: "Infection Respawn Zone"

}
