#Valhalla Item List

valhallaItems = {
    # MV Vehicle Pallette
    0: "Warthog",
    1: "Mongoose",
    2: "Ghost",
    3: "Chopper",
    5: "Wraith",
    6: "Banshee",
    7: "Hornet",
    8: "Scorpion",

    # MV Weapon Pallette
    9: "Assault Rifle",
    10: "Battle Rifle",
    11: "Shotgun",
    12: "Sniper Rifle",
    13: "SMG",
    14: "Spiker",
    15: "Magnum",
    16: "Plasma Pistol",
    17: "Needler",
    18: "Beam Rifle",
    19: "Brute Shot",
    20: "Rocket Launcher",
    21: "Spartan Laser",
    22: "Energy Sword",
    23: "Machine Gun Turret",
    24: "Gravity Hammer",
    25: "Missile Pod",
    26: "Sentinel Beam",
    27: "Carbine",
    28: "Plasma Rifle",
    29: "Mauler",
    30: "Fuel Rod Gun",
    31: "Silenced SMG",
    32: "Automag",
    33: "Brute Plasma Rifle",
    34: "Plasma Cannon",
    35: "Flamethrower",
    36: "7-Wood",

    # MV Equipment Pallette
    37: "Frag Grenade",
    38: "Plasma Grenade",
    39: "Spike Grenade",
    40: "Firebomb Grenade",
    41: "Bubble Shield",
    42: "Power Drain",
    43: "Trip Mine",
    44: "Grav Lift",
    45: "Regenerator",
    46: "Radar Jammer",
    47: "Flare",
    48: "Deployable Cover",
    49: "Overshields",
    50: "Active Camo",
    51: "Custom Powerup",
    52: "Auto-Turret",
    53: "Invincibility",
    54: "Cloaking",

    # MV Scenery Pallette
    55: "Fusion Coil",
    56: "Crate, Single",
    57: "Crate",
    58: "Turret Case",
    59: "Radio Antennae",
    60: "Camping Stool",
    61: "Drum, 55 Gal",
    62: "Equipment Case",
    63: "Radio Set, Small",
    64: "Drop Pod, Closed",
    65: "Drop Pod, Panel",
    66: "Barricade",
    67: "Medical Crate",
    68: "Grav Lift",
    69: "Weapon Holder",

    # MV Teleporter Pallette
    70: "Sender Node",
    71: "Receiver Node",
    72: "Two-Way Node",

    # MV Goals Pallette
    73: "CTF Spoawn Point",
    74: "CTF Return Area",
    75: "Assault Spawn Point",
    76: "Assault Goal Area",
    77: "Juggernaut Destination Static",
    78: "Hill Static",
    79: "Oddball Spawn Point",
    80: "Territory Static",
    81: "VIP Destination Static",

    # MV Spawners Pallette
    82: "Respawn Point",
    83: "Assault Initial Spawn Point",
    84: "CTF Initial Spawn Point",
    85: "Hill Initial Spawn Point",
    86: "Oddball Initial Spawn Point",
    87: "Slayer Initial Spawn Point",
    88: "Territories Initial Spawn Point",
    89: "VIP Initial Spawn Point",
    90: "Assault Respawn Zone",
    91: "CTF Respawn Zone",
    92: "CTF Flag At Home Respawn Zone",
    93: "CTF Flag Away Respawn Zone",
    94: "Hill Respawn Zone",
    95: "Oddball Respawn Zone",
    96: "Slayer Respawn Zone",
    97: "Territories Respawn Zone",
    98: "VIP Respawn Zone",
    99: "Infection Initial Spawn Point",
    100: "Infection Respawn Zone"

}
