# Narrows Item List

narrowsItems = {
    # MV Vehicle Pallette
    0: "Ghost",
    1: "Mongoose",

    # MV Weapon Pallette
    2: "Assault Rifle",
    3: "Battle Rifle",
    4: "Shotgun",
    5: "Sniper Rifle",
    6: "SMG",
    7: "Spiker",
    8: "Magnum",
    9: "Plasma Pistol",
    10: "Plasma Rifle",
    11: "Needler",
    12: "Brute Shot",
    13: "Rocket Launcher",
    14: "Spartan Laser",
    15: "Energy Sword",
    16: "Plasma Cannon",
    17: "Gravity Hammer",
    18: "Fuel Rod Gun",
    19: "Mauler",
    20: "Machine Gun Turret",
    21: "Flamethrower",
    22: "Beam Rifle",
    23: "Sentinel Beam",
    24: "Carbine",
    25: "Silenced SMG",
    26: "Automag",
    27: "Brute Plasma Rifle",
    28: "Missile Pod",
    29: "7-Wood",
   
   # MV Equipment Pallette
    30: "Frag Grenade",
    31: "Plasma Grenade",
    32: "Spike Grenade",
    33: "Firebomb Grenade",
    34: "Bubble Shield",
    35: "Power Drain",
    36: "Trip Mine",
    37: "Grav Lift",
    38: "Regenerator",
    39: "Radar Jammer",
    40: "Flare",
    41: "Deployable Cover",
    42: "Overshields",
    43: "Active Camo",
    44: "Custom Powerup",
    45: "Auto-Turret",
    46: "Invincibility",
    47: "Cloaking",

    # MV Scenery Pallette
    48: "Camping Stool",
    49: "Crate, Single",
    50: "Crate",
    51: "Radio Set",
    52: "Rucksack",
    53: "Drum, 55 Gal",
    54: "Roadblock",
    55: "Pallet",
    56: "Street Cone",
    57: "Turret Case",
    58: "Drum, 12 Gal",
    59: "Radio Set, Small",
    60: "Generator, Small",
    61: "Floodlights",
    62: "Ammo Crate",
    63: "Propane Burner",
    64: "Fusion Coil",
    65: "Weapon Holder",
    66: "PGrav Lift",
    
    

    # MV Teleporters Pallette
    67: "Sender Node",
    68: "Receiver Node",
    69: "Two-Way Node",

    # MV Goals Pallette
    70: "CTF Spoawn Point",
    71: "CTF Return Area",
    72: "Assault Spawn Point",
    73: "Assault Goal Area",
    74: "Juggernaut Destination Static",
    75: "Hill Static",
    76: "Oddball Spawn Point",
    77: "Territory Static",
    78: "VIP Destination Static",


    # MV Spawners Pallette
    79: "Respawn Point",
    80: "Assault Initial Spawn Point",
    81: "CTF Initial Spawn Point",
    82: "Hill Initial Spawn Point",
    83: "Oddball Initial Spawn Point",
    84: "Slayer Initial Spawn Point",
    85: "Territories Initial Spawn Point",
    86: "VIP Initial Spawn Point",
    87: "Assault Respawn Zone",
    88: "CTF Respawn Zone",
    89: "CTF Flag At Home Respawn Zone",
    90: "CTF Flag Away Respawn Zone",
    91: "Hill Respawn Zone",
    92: "Oddball Respawn Zone",
    93: "Slayer Respawn Zone",
    94: "Territories Respawn Zone",
    95: "VIP Respawn Zone",
    96: "Infection Initial Spawn Point",
    97: "Infection Respawn Zone"
}
