# Sandbox Item List

sandboxItems = {
    0: "Warthog",
    1: "Warthog, Gauss",
    2: "Mongoose",
    3: "Ghost",
    4: "Chopper",
    5: "Wraith",
    6: "Scorpion",
    7: "Wraith, Anti-Air",
    8: "Warthog, Transport",
    9: "Shade Turret",
    10: "Warthog, Wrecked",

    11: "Assault Rifle",
    12: "Battle Rifle",
    13: "Shotgun",
    14: "Sniper Rifle",
    15: "SMG",
    16: "Spiker",
    17: "Magnum",
    18: "Plasma Pistol",
    19: "Plasma Rifle",
    20: "Needler",
    21: "Brute Shot",
    22: "Rocket Launcher",
    23: "Spartan Laser",
    24: "Energy Sword",
    25: "Plasma Cannon",
    26: "Gravity Hammer",
    27: "Covenant Carbine",
    28: "Mauler",
    29: "Fuel Rod Gun",
    30: "Beam Rifle",
    31: "Sentinel Beam",
    32: "Machine Gun Turret",
    33: "Flamethrower",
    34: "Silenced SMG",
    35: "Automag",
    36: "Brute Plasma Rifle",
    37: "Missle Pod",

    38: "Frag Grenade",
    39: "Plasma Grenade",
    40: "Spike Grenade",
    41: "Firebomb Grenade",
    42: "Bubble Shield",
    43: "Power Drain",
    44: "Trip Mine",
    45: "Grav Lift",
    46: "Regenerator",
    47: "Radar Jammer",
    48: "Flare",
    49: "Deployable Cover",
    50: "Overshields",
    51: "Active Camo",
    52: "Custom Po1werup",
    53: "Auto-Turret",
    54: "SPNKR Ammo",

    # MAP VARIANT SCENERY STARTS
    57: "Double Box",
    58: "Double Box, Open",
    59: "Single Box",
    60: "Single Box, Open",
    61: "Fence Wall",
    62: "Fence Box",
    63: "Stairs",
    64: "Wall",
    65: "Wall, Double",
    66: "Wall, Corner",
    67: "Bridge",
    68: "Dumpster",
    69: "Door",
    70: "Forklift",
    71: "Truck",
    72: "Crate",
    73: "Wire Spool",
    74: "Sign B",
    75: "Sign A",
    76: "Window Panel",
    77: "Fusion Coil",
    78: "Barrel",
    79: "Barrel, Small",
    80: "Barrier",
    81: "Barrier, Short",
    82: "Pallet",
    83: "Roadblock",
    84: "Street Cone",
    85: "Propane Tank",
    86: "Weapon Holder",
    87: "Grav Lift",
    88: "Cannon, Man",
    89: "Shield Door, Large",
    90: "Shield Door",
    91: "Soccer Ball",
    92: "Container, Long",
    93: "Crate, Fish",
    94: "Palette, Fish",
    95: "Water Crate",
    96: "Supply Case",
    97: "Generator",
    98: "Server",
    99: "Door, Small",
    100: "Door, Medium",
    101: "Door, Large",
    102: "Cart, Electric",
    103: "Dinghy",
    104: "Tin Cup",
    105: "7-Wood",
    106: "Golf Ball",
    107: "Blue Light",
    108: "Red Light",
    109: "Tube Shield",
    110: "Scaffolding",
    111: "Wood Bridge, Large",
    112: "Wood Bridge, Thin",
    113: "Door",
    114: "Barricade",
    115: "Steel BArrier",
    116: "Block, Flat",
    117: "Ramp, Covenant",
    118: "FX, Nova",
    119: "FX, Pen And Ink",
    120: "FX, Olde Timey",
    121: "FX, Colorblind",
    122: "FX, Gloomy",
    123: "FX, Juicy",
    # MAP VARIANT SCENERY ENDS

    # MAP VARIANT TELEPORTERS START
    124: "Sender Node",
    125: "Receiver Node",
    126: "Two-Way Node",
    # MAP VARIANT TELEPORTERS END

    # MAP VARIANT SPAWNERS START
    127: "Respawn Point",
    128: "Assault Initial Spawn Point",
    129: "CTF Initial Spawn Point",
    130: "KOTH Initial Spawn Point",
    131: "Oddball Initial Spawn Point",
    132: "Slayer Initial Spawn Point",
    133: "Territories Initial Spawn Point",
    134: "VIP Initial Spawn Point",
    135: "Assault Respawn Zone",
    136: "CTF Respawn Zone",
    137: "CTF Flag at Home Respawn Zone",
    138: "CTF Flag Away Respawn Zone",
    139: "KOTH Respawn Zone",
    140: "Oddball Respawn Zone",
    141: "Slayer Respawn Zone",
    142: "Territories Respawn Zone",
    143: "VIP Respawn Zone",
    144: "Infection Initial Spawn Point",
    145: "Infection Respawn Zone",
    # MAP VARIANT SPAWNERS END

    # MAP VARIANT GOALS START
    146: "Flag Spawn Point",
    147: "Flag Return Point",
    148: "Assault Bomb Spawn Point",
    149: "Assault Bomb Goal Area",
    150: "Hill Marker",
    151: "Ball Spawn Point",
    152: "Territory Static",
    153: "VIP Destination Static",
    # MAP VARIANT GOALS END

    # SCENERY START
    154: "Spawn Point Invisible"
}