# Snowbound Item List

snowboundItems = {
    # MV Vehicle Pallette
    0: "Chopper",
    1: "Ghost",
    2: "Mongoose",
    3: "Prowler",
    4: "Wraith",

    # MV Weapon Pallette
    5: "Assault Rifle",
    6: "Battle Rifle",
    7: "Beam Rifle",
    8: "Brute Shot",
    9: "Carbine",
    10: "Energy Sword",
    11: "Flamethrower",
    12: "Fuel Rod Gun",
    13: "Gravity Hammer",
    14: "Machine Gun Turret",
    15: "Magnum",
    16: "Mauler",
    17: "Needler",
    18: "Plasma Cannon",
    19: "Plasma Pistol",
    20: "Plasma Rifle",
    21: "Rocket Launcher",
    22: "Shotgun",
    23: "SMG",
    24: "Sniper Rifle",
    25: "Spartan Laser",
    26: "Spiker",
    27: "Sentinel Beam",
    28: "Silenced SMG",
    29: "Automag",
    30: "Brute PLasma Rifle",
    31: "Missile Pod",
    32: "7-Wood",

    # MV Equipment Pallette
    33: "Frag Grenade",
    34: "Plasma Grenade",
    35: "Spike Grenade",
    36: "Firebomb Grenade",
    37: "Bubble Shield",
    38: "Power Drain",
    39: "Trip Mine",
    40: "Grav Lift",
    41: "Regenerator",
    42: "Radar Jammer",
    43: "Flare",
    44: "Deployable Cover",
    45: "Overshields",
    46: "Active Camo",
    47: "Custom Powerup",
    48: "Auto-Turret",
    49: "Invincibility",
    50: "Cloaking",

    # MV Scenery Pallette
    51: "Barrier",
    52: "Camping Stool",
    53: "Comm Node",
    54: "Plasma Battery",
    55: "Power core",
    56: "Supply Case",
    57: "Supply Case, Bare",
    58: "Supply Case, Open",
    59: "Weapon Holder",
    60: "Crate",
    61: "Grav Lift",

    # MV Teleporter Pallette
    62: "Sender Node",
    63: "Receiver Node",
    64: "Two-Way Node",

    # MV Goals Pallette
    65: "Assault Goal Area",
    66: "Assault Spawn Point",
    67: "CTF Return Area",
    68: "CTF Spawn Point",
    69: "Juggernaut Destination Static",
    70: "Hill Static",
    71: "Oddball Spawn Point",
    72: "Territory Static",
    73: "VIP Destination Static",


    # MV Spawners Pallette
    74: "Respawn Point",
    75: "Assault Initial Spawn Point",
    76: "CTF Initial Spawn Point",
    77: "Hill Initial Spawn Point",
    78: "Oddball Initial Spawn Point",
    79: "Slayer Initial Spawn Point",
    80: "Territories Initial Spawn Point",
    81: "VIP Initial Spawn Point",
    82: "Assault Respawn Zone",
    83: "CTF Respawn Zone",
    84: "CTF Flag At Home Respawn Zone",
    85: "CTF Flag Away Respawn Zone",
    86: "Hill Respawn Zone",
    87: "Oddball Respawn Zone",
    88: "Slayer Respawn Zone",
    89: "Territories Respawn Zone",
    90: "VIP Respawn Zone",
    91: "Infection Initial Spawn Point",
    92: "Infection Respawn Zone"

}
